<a href="https://colab.research.google.com/github/i2mmmmm/train_project/blob/main/20230826_ar_c.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import numpy as np
import pandas as pd
import tensorflow as tf
from sklearn.preprocessing import StandardScaler
from tensorflow.keras.models import Sequential
from tensorflow.keras.callbacks import EarlyStopping
from tensorflow.keras.layers import LayerNormalization, MultiHeadAttention, Flatten
import tensorflow as tf
from tensorflow.keras.layers import Conv1D, MaxPooling1D, Flatten, Dense, Dropout, Activation
from tensorflow.keras.callbacks import EarlyStopping
from tensorflow.keras.layers import LSTM, Flatten, Dense, Dropout
from tensorflow.keras.models import Model
from sklearn.preprocessing import StandardScaler

In [5]:
from google.colab import drive

from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [6]:
s30_train = pd.read_csv('/content/drive/My Drive/철도/s30_train.csv')
s40_train = pd.read_csv('/content/drive/My Drive/철도/s40_train.csv')
s50_train = pd.read_csv('/content/drive/My Drive/철도/s50_train.csv')
s70_train = pd.read_csv('/content/drive/My Drive/철도/s70_train.csv')
s100_train = pd.read_csv('/content/drive/My Drive/철도/s100_train.csv')
c30_train = pd.read_csv('/content/drive/My Drive/철도/c30_train.csv')
c40_train = pd.read_csv('/content/drive/My Drive/철도/c40_train.csv')
c50_train = pd.read_csv('/content/drive/My Drive/철도/c50_train.csv')
c70_train = pd.read_csv('/content/drive/My Drive/철도/c70_train.csv')
c100_train = pd.read_csv('/content/drive/My Drive/철도/c100_train.csv')

In [7]:
def prepare_data(filename):
    data = filename
    X = data.drop(columns=['Curvature', 'Vertical offset', 'Cross level offset', 'A_M1_B1_W1_Z_L', 'A_M1_B1_BC_Z_L', 'A_M1_B1_W2_Z_L', 'A_M1_B1_W1_Z_R', 'A_M1_B1_BC_Z_R', 'A_M1_B1_W2_Z_R', 'A__B1_W2_Y_A_axle_L', 'A__B1_W1_Z_A_axle_R'])
    y = data[["YL_M1_B1_W1", "YR_M1_B1_W1"]]

    # 데이터 스케일링
    scaler_X = StandardScaler()
    X = scaler_X.fit_transform(X)

    # scaler_y = StandardScaler()  # y 데이터에 대한 새로운 스케일러
    # y = scaler_y.fit_transform(y)  # 2차원 배열로 변환

    return X, y

def reshape_data(X, y, N_TIMESTEPS):
    X_list, y_list = [], []
    X_padded = np.vstack([np.zeros((N_TIMESTEPS, X.shape[1])), X])

    for i in range(len(X_padded) - N_TIMESTEPS):
        X_list.append(X_padded[i:i+N_TIMESTEPS])
        y_list.append(y.iloc[i])

    return np.array(X_list), np.array(y_list)


data_s_X, data_s_y = prepare_data(c30_train)   #####################################################

N_TIMESTEPS = 10
N_FEATURES = 27

X_s, y_s = reshape_data(data_s_X, data_s_y, N_TIMESTEPS)

# 트레이닝/테스트 데이터 나누기
X_train_s = X_s[:10001]
y_train_s = y_s[:10001]
X_test_s = X_s[10001:]
y_test_s = y_s[10001:]


# Early stopping
es = EarlyStopping(monitor='val_loss', mode='min', verbose=1, patience=20)

from tensorflow.keras.layers import RepeatVector, TimeDistributed

# DeepAR 스타일의 모델 구축
inputs = tf.keras.Input(shape=(N_TIMESTEPS, N_FEATURES))

# LSTM을 통한 인코딩
x = LSTM(64, return_sequences=True)(inputs)
x = LSTM(128, return_sequences=False)(x)
x = Dropout(0.5)(x)

# 미래 타임스텝에 대한 예측을 위한 RepeatVector
x = RepeatVector(N_TIMESTEPS)(x)

# LSTM을 통한 디코딩
x = LSTM(128, return_sequences=True)(x)
x = LSTM(64, return_sequences=True)(x)
x = Dropout(0.5)(x)

# 각 타임스텝에 대한 출력 값 생성
x = TimeDistributed(Dense(2))(x)

model_deepar = Model(inputs=inputs, outputs=x[:, -1, :])  # 마지막 타임스텝의 출력만 사용

model_deepar.compile(optimizer=tf.keras.optimizers.Adam(learning_rate=0.001), loss='mse', metrics=['mae'])

model_deepar.fit(X_train_s, y_train_s, epochs=50, batch_size=64, validation_data=(X_test_s, y_test_s), callbacks=[es])


# 예측
predictions_s = model_deepar.predict(X_test_s)

Epoch 1/50
157/157 [==============================] - 26s 109ms/step - loss: 0.0016 - mae: 0.0243 - val_loss: 2.6741e-04 - val_mae: 0.0125
Epoch 2/50
157/157 [==============================] - 15s 96ms/step - loss: 6.4407e-04 - mae: 0.0144 - val_loss: 1.4533e-04 - val_mae: 0.0096
Epoch 3/50
157/157 [==============================] - 15s 98ms/step - loss: 4.7871e-04 - mae: 0.0123 - val_loss: 1.0081e-04 - val_mae: 0.0079
Epoch 4/50
157/157 [==============================] - 18s 115ms/step - loss: 4.1707e-04 - mae: 0.0112 - val_loss: 1.2103e-04 - val_mae: 0.0087
Epoch 5/50
157/157 [==============================] - 24s 151ms/step - loss: 3.7640e-04 - mae: 0.0107 - val_loss: 1.0700e-04 - val_mae: 0.0081
Epoch 6/50
157/157 [==============================] - 16s 104ms/step - loss: 3.9827e-04 - mae: 0.0101 - val_loss: 9.5238e-05 - val_mae: 0.0076
Epoch 7/50
157/157 [==============================] - 15s 96ms/step - loss: 3.5072e-04 - mae: 0.0095 - val_loss: 1.2275e-04 - val_mae: 0.0089
Epoch 8/50
157/157 [==============================] - 16s 100ms/step - loss: 2.7819e-04 - mae: 0.0092 - val_loss: 7.8914e-05 - val_mae: 0.0071
Epoch 9/50
157/157 [==============================] - 16s 99ms/step - loss: 2.4224e-04 - mae: 0.0086 - val_loss: 6.4698e-05 - val_mae: 0.0064
Epoch 10/50
157/157 [==============================] - 16s 100ms/step - loss: 2.8572e-04 - mae: 0.0088 - val_loss: 6.1158e-05 - val_mae: 0.0062
Epoch 11/50
157/157 [==============================] - 20s 125ms/step - loss: 2.4179e-04 - mae: 0.0082 - val_loss: 6.5814e-05 - val_mae: 0.0064
Epoch 12/50
157/157 [==============================] - 19s 123ms/step - loss: 2.3805e-04 - mae: 0.0079 - val_loss: 6.9479e-05 - val_mae: 0.0065
Epoch 13/50
157/157 [==============================] - 15s 96ms/step - loss: 2.3015e-04 - mae: 0.0080 - val_loss: 4.4011e-05 - val_mae: 0.0052
Epoch 14/50
157/157 [==============================] - 16s 99ms/step - loss: 2.1407e-04 - mae: 0.0076 - val_loss: 6.5489e-05 - val_mae: 0.0066
Epoch 15/50
157/157 [==============================] - 15s 97ms/step - loss: 1.6081e-04 - mae: 0.0071 - val_loss: 3.3782e-05 - val_mae: 0.0046
Epoch 16/50
157/157 [==============================] - 16s 100ms/step - loss: 1.5102e-04 - mae: 0.0069 - val_loss: 3.6873e-05 - val_mae: 0.0048
Epoch 17/50
157/157 [==============================] - 16s 99ms/step - loss: 1.6254e-04 - mae: 0.0069 - val_loss: 4.6026e-05 - val_mae: 0.0054
Epoch 18/50
157/157 [==============================] - 16s 100ms/step - loss: 1.7115e-04 - mae: 0.0068 - val_loss: 4.6286e-05 - val_mae: 0.0055
Epoch 19/50
157/157 [==============================] - 19s 124ms/step - loss: 1.6104e-04 - mae: 0.0067 - val_loss: 3.4474e-05 - val_mae: 0.0047
Epoch 20/50
157/157 [==============================] - 18s 116ms/step - loss: 1.9875e-04 - mae: 0.0070 - val_loss: 3.1755e-05 - val_mae: 0.0045
Epoch 21/50
157/157 [==============================] - 15s 96ms/step - loss: 1.7211e-04 - mae: 0.0065 - val_loss: 4.2773e-05 - val_mae: 0.0051
Epoch 22/50
157/157 [==============================] - 19s 122ms/step - loss: 1.4874e-04 - mae: 0.0065 - val_loss: 3.7705e-05 - val_mae: 0.0049
Epoch 23/50
157/157 [==============================] - 15s 98ms/step - loss: 1.6056e-04 - mae: 0.0064 - val_loss: 3.3498e-05 - val_mae: 0.0046
Epoch 24/50
157/157 [==============================] - 16s 100ms/step - loss: 1.4371e-04 - mae: 0.0062 - val_loss: 3.2791e-05 - val_mae: 0.0045
Epoch 25/50
157/157 [==============================] - 16s 100ms/step - loss: 1.3946e-04 - mae: 0.0060 - val_loss: 2.5917e-05 - val_mae: 0.0040
Epoch 26/50
157/157 [==============================] - 18s 114ms/step - loss: 1.6573e-04 - mae: 0.0061 - val_loss: 3.8403e-05 - val_mae: 0.0048
Epoch 27/50
157/157 [==============================] - 18s 114ms/step - loss: 1.8095e-04 - mae: 0.0064 - val_loss: 4.1318e-05 - val_mae: 0.0050
Epoch 28/50
157/157 [==============================] - 22s 137ms/step - loss: 1.8572e-04 - mae: 0.0066 - val_loss: 2.9147e-05 - val_mae: 0.0043
Epoch 29/50
157/157 [==============================] - 16s 100ms/step - loss: 1.3154e-04 - mae: 0.0059 - val_loss: 3.7926e-05 - val_mae: 0.0049
Epoch 30/50
157/157 [==============================] - 15s 96ms/step - loss: 1.5583e-04 - mae: 0.0060 - val_loss: 2.4889e-05 - val_mae: 0.0039
Epoch 31/50
157/157 [==============================] - 16s 100ms/step - loss: 1.5850e-04 - mae: 0.0059 - val_loss: 2.6772e-05 - val_mae: 0.0041
Epoch 32/50
157/157 [==============================] - 16s 100ms/step - loss: 1.4106e-04 - mae: 0.0058 - val_loss: 3.1556e-05 - val_mae: 0.0045
Epoch 33/50
157/157 [==============================] - 16s 100ms/step - loss: 1.6401e-04 - mae: 0.0060 - val_loss: 3.6206e-05 - val_mae: 0.0047
Epoch 34/50
157/157 [==============================] - 22s 139ms/step - loss: 1.6490e-04 - mae: 0.0061 - val_loss: 2.9942e-05 - val_mae: 0.0043
Epoch 35/50
157/157 [==============================] - 17s 106ms/step - loss: 1.4564e-04 - mae: 0.0058 - val_loss: 2.4122e-05 - val_mae: 0.0039
Epoch 36/50
157/157 [==============================] - 16s 100ms/step - loss: 1.2218e-04 - mae: 0.0057 - val_loss: 2.3640e-05 - val_mae: 0.0038
Epoch 37/50
157/157 [==============================] - 15s 96ms/step - loss: 1.2799e-04 - mae: 0.0057 - val_loss: 2.9367e-05 - val_mae: 0.0043
Epoch 38/50
157/157 [==============================] - 16s 100ms/step - loss: 1.2525e-04 - mae: 0.0057 - val_loss: 2.9245e-05 - val_mae: 0.0043
Epoch 39/50
157/157 [==============================] - 15s 98ms/step - loss: 1.4945e-04 - mae: 0.0060 - val_loss: 1.8376e-05 - val_mae: 0.0034
Epoch 40/50
157/157 [==============================] - 17s 106ms/step - loss: 1.3359e-04 - mae: 0.0056 - val_loss: 2.6577e-05 - val_mae: 0.0041
Epoch 41/50
157/157 [==============================] - 23s 147ms/step - loss: 1.5793e-04 - mae: 0.0057 - val_loss: 3.2640e-05 - val_mae: 0.0046
Epoch 42/50
157/157 [==============================] - 17s 105ms/step - loss: 1.3528e-04 - mae: 0.0057 - val_loss: 2.6524e-05 - val_mae: 0.0040
Epoch 43/50
157/157 [==============================] - 16s 100ms/step - loss: 1.3732e-04 - mae: 0.0057 - val_loss: 3.3814e-05 - val_mae: 0.0046
Epoch 44/50
157/157 [==============================] - 15s 96ms/step - loss: 1.3558e-04 - mae: 0.0057 - val_loss: 2.2237e-05 - val_mae: 0.0037
Epoch 45/50
157/157 [==============================] - 16s 100ms/step - loss: 1.2580e-04 - mae: 0.0055 - val_loss: 1.7082e-05 - val_mae: 0.0032
Epoch 46/50
157/157 [==============================] - 18s 114ms/step - loss: 1.5039e-04 - mae: 0.0054 - val_loss: 2.4129e-05 - val_mae: 0.0038
Epoch 47/50
157/157 [==============================] - 17s 106ms/step - loss: 1.2371e-04 - mae: 0.0056 - val_loss: 2.2193e-05 - val_mae: 0.0037
Epoch 48/50
157/157 [==============================] - 18s 114ms/step - loss: 1.2452e-04 - mae: 0.0055 - val_loss: 2.2953e-05 - val_mae: 0.0037
Epoch 49/50
157/157 [==============================] - 18s 113ms/step - loss: 1.0814e-04 - mae: 0.0054 - val_loss: 1.9452e-05 - val_mae: 0.0034
Epoch 50/50
157/157 [==============================] - 16s 100ms/step - loss: 1.4286e-04 - mae: 0.0058 - val_loss: 2.7744e-05 - val_mae: 0.0042
63/63 [==============================] - 3s 17ms/step

In [8]:


def prepare_data(filename):
    data = filename
    X = data.drop(columns=['A_M1_B1_W1_Z_L', 'A_M1_B1_BC_Z_L', 'A_M1_B1_W1_Z_R', 'A_M1_B1_BC_Z_R', 'A_M1_B1_W2_Z_R', 'A__B1_W1_Z_A_axle_L', 'A__B1_W1_Z_A_axle_R', 'A__B1_W2_Z_A_axle_R', 'V_M1_B1_W1_L', 'V_M1_B1_W1_R', 'QL_M1_B1_W1', 'QR_M1_B1_W1'])
    y = data[["YL_M1_B1_W2", "YR_M1_B1_W2"]]

    # 데이터 스케일링
    scaler_X = StandardScaler()
    X = scaler_X.fit_transform(X)

    # scaler_y = StandardScaler()  # y 데이터에 대한 새로운 스케일러
    # y = scaler_y.fit_transform(y)  # 2차원 배열로 변환

    return X, y

def reshape_data(X, y, N_TIMESTEPS):
    X_list, y_list = [], []
    X_padded = np.vstack([np.zeros((N_TIMESTEPS, X.shape[1])), X])

    for i in range(len(X_padded) - N_TIMESTEPS):
        X_list.append(X_padded[i:i+N_TIMESTEPS])
        y_list.append(y.iloc[i])

    return np.array(X_list), np.array(y_list)


data_s_X, data_s_y = prepare_data(c30_train)   #####################################################

N_TIMESTEPS = 10
N_FEATURES = 26

X_s, y_s = reshape_data(data_s_X, data_s_y, N_TIMESTEPS)

# 트레이닝/테스트 데이터 나누기
X_train_s = X_s[:10001]
y_train_s = y_s[:10001]
X_test_s = X_s[10001:]
y_test_s = y_s[10001:]


# Early stopping
es = EarlyStopping(monitor='val_loss', mode='min', verbose=1, patience=20)

from tensorflow.keras.layers import RepeatVector, TimeDistributed

# DeepAR 스타일의 모델 구축
inputs = tf.keras.Input(shape=(N_TIMESTEPS, N_FEATURES))

# LSTM을 통한 인코딩
x = LSTM(64, return_sequences=True)(inputs)
x = LSTM(128, return_sequences=False)(x)
x = Dropout(0.5)(x)

# 미래 타임스텝에 대한 예측을 위한 RepeatVector
x = RepeatVector(N_TIMESTEPS)(x)

# LSTM을 통한 디코딩
x = LSTM(128, return_sequences=True)(x)
x = LSTM(64, return_sequences=True)(x)
x = Dropout(0.5)(x)

# 각 타임스텝에 대한 출력 값 생성
x = TimeDistributed(Dense(2))(x)

model_deepar = Model(inputs=inputs, outputs=x[:, -1, :])  # 마지막 타임스텝의 출력만 사용

model_deepar.compile(optimizer=tf.keras.optimizers.Adam(learning_rate=0.001), loss='mse', metrics=['mae'])

model_deepar.fit(X_train_s, y_train_s, epochs=50, batch_size=64, validation_data=(X_test_s, y_test_s), callbacks=[es])


# 예측
predictions_s2 = model_deepar.predict(X_test_s)

Epoch 1/50
157/157 [==============================] - 28s 108ms/step - loss: 0.0015 - mae: 0.0265 - val_loss: 5.6824e-04 - val_mae: 0.0192
Epoch 2/50
157/157 [==============================] - 15s 95ms/step - loss: 5.7714e-04 - mae: 0.0162 - val_loss: 4.1433e-04 - val_mae: 0.0164
Epoch 3/50
157/157 [==============================] - 18s 114ms/step - loss: 4.3851e-04 - mae: 0.0141 - val_loss: 4.6738e-04 - val_mae: 0.0173
Epoch 4/50
157/157 [==============================] - 18s 114ms/step - loss: 3.9270e-04 - mae: 0.0131 - val_loss: 3.0046e-04 - val_mae: 0.0140
Epoch 5/50
157/157 [==============================] - 16s 100ms/step - loss: 3.0495e-04 - mae: 0.0116 - val_loss: 2.5598e-04 - val_mae: 0.0128
Epoch 6/50
157/157 [==============================] - 30s 192ms/step - loss: 2.9616e-04 - mae: 0.0114 - val_loss: 2.8523e-04 - val_mae: 0.0136
Epoch 7/50
157/157 [==============================] - 16s 100ms/step - loss: 3.0360e-04 - mae: 0.0112 - val_loss: 3.0561e-04 - val_mae: 0.0140
Epoch 8/50
157/157 [==============================] - 15s 98ms/step - loss: 3.1872e-04 - mae: 0.0114 - val_loss: 2.5912e-04 - val_mae: 0.0129
Epoch 9/50
157/157 [==============================] - 18s 115ms/step - loss: 2.5907e-04 - mae: 0.0105 - val_loss: 1.9876e-04 - val_mae: 0.0114
Epoch 10/50
157/157 [==============================] - 18s 118ms/step - loss: 2.4684e-04 - mae: 0.0101 - val_loss: 1.5677e-04 - val_mae: 0.0101
Epoch 11/50
157/157 [==============================] - 20s 128ms/step - loss: 2.4395e-04 - mae: 0.0100 - val_loss: 1.4642e-04 - val_mae: 0.0096
Epoch 12/50
157/157 [==============================] - 16s 103ms/step - loss: 2.2639e-04 - mae: 0.0097 - val_loss: 2.0159e-04 - val_mae: 0.0116
Epoch 13/50
157/157 [==============================] - 17s 105ms/step - loss: 2.1209e-04 - mae: 0.0094 - val_loss: 1.8043e-04 - val_mae: 0.0106
Epoch 14/50
157/157 [==============================] - 15s 98ms/step - loss: 2.1875e-04 - mae: 0.0094 - val_loss: 1.3782e-04 - val_mae: 0.0093
Epoch 15/50
157/157 [==============================] - 15s 97ms/step - loss: 2.1276e-04 - mae: 0.0093 - val_loss: 1.2084e-04 - val_mae: 0.0087
Epoch 16/50
157/157 [==============================] - 17s 111ms/step - loss: 2.0836e-04 - mae: 0.0091 - val_loss: 1.0947e-04 - val_mae: 0.0085
Epoch 17/50
157/157 [==============================] - 22s 142ms/step - loss: 1.9661e-04 - mae: 0.0088 - val_loss: 1.3041e-04 - val_mae: 0.0091
Epoch 18/50
157/157 [==============================] - 16s 99ms/step - loss: 1.9396e-04 - mae: 0.0088 - val_loss: 1.0722e-04 - val_mae: 0.0083
Epoch 19/50
157/157 [==============================] - 15s 98ms/step - loss: 1.9162e-04 - mae: 0.0087 - val_loss: 1.8899e-04 - val_mae: 0.0117
Epoch 20/50
157/157 [==============================] - 15s 97ms/step - loss: 1.9157e-04 - mae: 0.0087 - val_loss: 1.2670e-04 - val_mae: 0.0091
Epoch 21/50
157/157 [==============================] - 15s 97ms/step - loss: 2.0950e-04 - mae: 0.0091 - val_loss: 9.2518e-05 - val_mae: 0.0077
Epoch 22/50
157/157 [==============================] - 16s 101ms/step - loss: 1.8912e-04 - mae: 0.0085 - val_loss: 9.2435e-05 - val_mae: 0.0077
Epoch 23/50
157/157 [==============================] - 22s 142ms/step - loss: 1.9506e-04 - mae: 0.0088 - val_loss: 6.9776e-05 - val_mae: 0.0066
Epoch 24/50
157/157 [==============================] - 17s 107ms/step - loss: 1.8864e-04 - mae: 0.0084 - val_loss: 9.0587e-05 - val_mae: 0.0076
Epoch 25/50
157/157 [==============================] - 18s 113ms/step - loss: 1.9084e-04 - mae: 0.0086 - val_loss: 1.1205e-04 - val_mae: 0.0085
Epoch 26/50
157/157 [==============================] - 16s 99ms/step - loss: 1.7508e-04 - mae: 0.0083 - val_loss: 6.9171e-05 - val_mae: 0.0067
Epoch 27/50
157/157 [==============================] - 15s 98ms/step - loss: 1.7889e-04 - mae: 0.0082 - val_loss: 7.2345e-05 - val_mae: 0.0067
Epoch 28/50
157/157 [==============================] - 16s 101ms/step - loss: 1.7978e-04 - mae: 0.0083 - val_loss: 7.7441e-05 - val_mae: 0.0070
Epoch 29/50
157/157 [==============================] - 20s 125ms/step - loss: 1.8310e-04 - mae: 0.0084 - val_loss: 8.0559e-05 - val_mae: 0.0071
Epoch 30/50
157/157 [==============================] - 18s 113ms/step - loss: 1.7347e-04 - mae: 0.0080 - val_loss: 9.0046e-05 - val_mae: 0.0078
Epoch 31/50
157/157 [==============================] - 15s 97ms/step - loss: 1.7742e-04 - mae: 0.0082 - val_loss: 8.1689e-05 - val_mae: 0.0074
Epoch 32/50
157/157 [==============================] - 18s 115ms/step - loss: 1.6450e-04 - mae: 0.0080 - val_loss: 7.0717e-05 - val_mae: 0.0066
Epoch 33/50
157/157 [==============================] - 15s 97ms/step - loss: 1.8557e-04 - mae: 0.0082 - val_loss: 8.5281e-05 - val_mae: 0.0074
Epoch 34/50
157/157 [==============================] - 17s 110ms/step - loss: 1.6568e-04 - mae: 0.0079 - val_loss: 7.7328e-05 - val_mae: 0.0071
Epoch 35/50
157/157 [==============================] - 18s 112ms/step - loss: 1.6908e-04 - mae: 0.0080 - val_loss: 6.3316e-05 - val_mae: 0.0063
Epoch 36/50
157/157 [==============================] - 16s 101ms/step - loss: 1.6955e-04 - mae: 0.0081 - val_loss: 5.4462e-05 - val_mae: 0.0059
Epoch 37/50
157/157 [==============================] - 15s 98ms/step - loss: 1.6845e-04 - mae: 0.0079 - val_loss: 5.0346e-05 - val_mae: 0.0056
Epoch 38/50
157/157 [==============================] - 18s 114ms/step - loss: 1.6828e-04 - mae: 0.0080 - val_loss: 4.8642e-05 - val_mae: 0.0056
Epoch 39/50
157/157 [==============================] - 18s 115ms/step - loss: 1.7643e-04 - mae: 0.0079 - val_loss: 6.1949e-05 - val_mae: 0.0063
Epoch 40/50
157/157 [==============================] - 22s 142ms/step - loss: 1.5861e-04 - mae: 0.0079 - val_loss: 7.3525e-05 - val_mae: 0.0070
Epoch 41/50
157/157 [==============================] - 15s 97ms/step - loss: 1.7491e-04 - mae: 0.0079 - val_loss: 6.3377e-05 - val_mae: 0.0064
Epoch 42/50
157/157 [==============================] - 15s 97ms/step - loss: 1.6132e-04 - mae: 0.0079 - val_loss: 4.8299e-05 - val_mae: 0.0056
Epoch 43/50
157/157 [==============================] - 16s 100ms/step - loss: 1.5923e-04 - mae: 0.0078 - val_loss: 4.3220e-05 - val_mae: 0.0053
Epoch 44/50
157/157 [==============================] - 16s 104ms/step - loss: 1.6494e-04 - mae: 0.0079 - val_loss: 5.2630e-05 - val_mae: 0.0057
Epoch 45/50
157/157 [==============================] - 17s 108ms/step - loss: 1.6692e-04 - mae: 0.0078 - val_loss: 4.8747e-05 - val_mae: 0.0055
Epoch 46/50
157/157 [==============================] - 21s 136ms/step - loss: 1.5769e-04 - mae: 0.0076 - val_loss: 4.0742e-05 - val_mae: 0.0051
Epoch 47/50
157/157 [==============================] - 16s 101ms/step - loss: 1.6250e-04 - mae: 0.0079 - val_loss: 7.8907e-05 - val_mae: 0.0073
Epoch 48/50
157/157 [==============================] - 16s 101ms/step - loss: 1.5623e-04 - mae: 0.0077 - val_loss: 4.3391e-05 - val_mae: 0.0053
Epoch 49/50
157/157 [==============================] - 16s 101ms/step - loss: 1.5355e-04 - mae: 0.0076 - val_loss: 4.6653e-05 - val_mae: 0.0053
Epoch 50/50
157/157 [==============================] - 15s 97ms/step - loss: 1.5412e-04 - mae: 0.0077 - val_loss: 4.2984e-05 - val_mae: 0.0053
63/63 [==============================] - 3s 17ms/step

In [9]:
predictions_30c = pd.DataFrame(predictions_s, columns=['YL_M1_B1_W1', 'YR_M1_B1_W1'])
predictions_30c2 = pd.DataFrame(predictions_s2, columns=['YL_M1_B1_W2', 'YR_M1_B1_W2'])

In [10]:
def prepare_data(filename):
    data = filename
    X = data.drop(columns=['Curvature', 'Vertical offset', 'Cross level offset', 'A_M1_B1_W1_Z_L', 'A_M1_B1_BC_Z_L', 'A_M1_B1_W2_Z_L', 'A_M1_B1_W1_Z_R', 'A_M1_B1_BC_Z_R', 'A_M1_B1_W2_Z_R', 'A__B1_W2_Y_A_axle_L', 'A__B1_W1_Z_A_axle_R'])
    y = data[["YL_M1_B1_W1", "YR_M1_B1_W1"]]

    # 데이터 스케일링
    scaler_X = StandardScaler()
    X = scaler_X.fit_transform(X)

    # scaler_y = StandardScaler()  # y 데이터에 대한 새로운 스케일러
    # y = scaler_y.fit_transform(y)  # 2차원 배열로 변환

    return X, y

def reshape_data(X, y, N_TIMESTEPS):
    X_list, y_list = [], []
    X_padded = np.vstack([np.zeros((N_TIMESTEPS, X.shape[1])), X])

    for i in range(len(X_padded) - N_TIMESTEPS):
        X_list.append(X_padded[i:i+N_TIMESTEPS])
        y_list.append(y.iloc[i])

    return np.array(X_list), np.array(y_list)


data_s_X, data_s_y = prepare_data(c40_train)   #####################################################

N_TIMESTEPS = 10
N_FEATURES = 27

X_s, y_s = reshape_data(data_s_X, data_s_y, N_TIMESTEPS)

# 트레이닝/테스트 데이터 나누기
X_train_s = X_s[:10001]
y_train_s = y_s[:10001]
X_test_s = X_s[10001:]
y_test_s = y_s[10001:]


# Early stopping
es = EarlyStopping(monitor='val_loss', mode='min', verbose=1, patience=20)

from tensorflow.keras.layers import RepeatVector, TimeDistributed

# DeepAR 스타일의 모델 구축
inputs = tf.keras.Input(shape=(N_TIMESTEPS, N_FEATURES))

# LSTM을 통한 인코딩
x = LSTM(64, return_sequences=True)(inputs)
x = LSTM(128, return_sequences=False)(x)
x = Dropout(0.5)(x)

# 미래 타임스텝에 대한 예측을 위한 RepeatVector
x = RepeatVector(N_TIMESTEPS)(x)

# LSTM을 통한 디코딩
x = LSTM(128, return_sequences=True)(x)
x = LSTM(64, return_sequences=True)(x)
x = Dropout(0.5)(x)

# 각 타임스텝에 대한 출력 값 생성
x = TimeDistributed(Dense(2))(x)

model_deepar = Model(inputs=inputs, outputs=x[:, -1, :])  # 마지막 타임스텝의 출력만 사용

model_deepar.compile(optimizer=tf.keras.optimizers.Adam(learning_rate=0.001), loss='mse', metrics=['mae'])

model_deepar.fit(X_train_s, y_train_s, epochs=50, batch_size=64, validation_data=(X_test_s, y_test_s), callbacks=[es])


# 예측
predictions_s = model_deepar.predict(X_test_s)

Epoch 1/50
157/157 [==============================] - 33s 150ms/step - loss: 8.4365e-04 - mae: 0.0196 - val_loss: 8.1955e-05 - val_mae: 0.0072
Epoch 2/50
157/157 [==============================] - 18s 113ms/step - loss: 1.9445e-04 - mae: 0.0100 - val_loss: 8.4174e-05 - val_mae: 0.0074
Epoch 3/50
157/157 [==============================] - 15s 98ms/step - loss: 1.4905e-04 - mae: 0.0085 - val_loss: 7.1478e-05 - val_mae: 0.0067
Epoch 4/50
157/157 [==============================] - 16s 102ms/step - loss: 1.2586e-04 - mae: 0.0076 - val_loss: 6.1405e-05 - val_mae: 0.0063
Epoch 5/50
157/157 [==============================] - 16s 101ms/step - loss: 1.0516e-04 - mae: 0.0071 - val_loss: 6.9869e-05 - val_mae: 0.0067
Epoch 6/50
157/157 [==============================] - 15s 98ms/step - loss: 9.3155e-05 - mae: 0.0067 - val_loss: 5.7612e-05 - val_mae: 0.0060
Epoch 7/50
157/157 [==============================] - 22s 140ms/step - loss: 8.6396e-05 - mae: 0.0064 - val_loss: 5.2791e-05 - val_mae: 0.0057
Epoch 8/50
157/157 [==============================] - 16s 102ms/step - loss: 8.3921e-05 - mae: 0.0062 - val_loss: 5.0664e-05 - val_mae: 0.0057
Epoch 9/50
157/157 [==============================] - 19s 122ms/step - loss: 7.6384e-05 - mae: 0.0060 - val_loss: 4.9323e-05 - val_mae: 0.0056
Epoch 10/50
157/157 [==============================] - 15s 99ms/step - loss: 6.9684e-05 - mae: 0.0057 - val_loss: 3.7269e-05 - val_mae: 0.0048
Epoch 11/50
157/157 [==============================] - 16s 101ms/step - loss: 6.5718e-05 - mae: 0.0055 - val_loss: 3.1302e-05 - val_mae: 0.0045
Epoch 12/50
157/157 [==============================] - 18s 115ms/step - loss: 6.2758e-05 - mae: 0.0053 - val_loss: 2.7528e-05 - val_mae: 0.0041
Epoch 13/50
157/157 [==============================] - 17s 109ms/step - loss: 6.6803e-05 - mae: 0.0053 - val_loss: 3.1763e-05 - val_mae: 0.0046
Epoch 14/50
157/157 [==============================] - 16s 105ms/step - loss: 5.7127e-05 - mae: 0.0050 - val_loss: 2.6640e-05 - val_mae: 0.0041
Epoch 15/50
157/157 [==============================] - 17s 108ms/step - loss: 5.2828e-05 - mae: 0.0049 - val_loss: 3.0237e-05 - val_mae: 0.0044
Epoch 16/50
157/157 [==============================] - 18s 116ms/step - loss: 4.9135e-05 - mae: 0.0047 - val_loss: 3.5752e-05 - val_mae: 0.0048
Epoch 17/50
157/157 [==============================] - 17s 106ms/step - loss: 4.9498e-05 - mae: 0.0046 - val_loss: 2.3705e-05 - val_mae: 0.0039
Epoch 18/50
157/157 [==============================] - 21s 131ms/step - loss: 5.3874e-05 - mae: 0.0046 - val_loss: 2.8001e-05 - val_mae: 0.0042
Epoch 19/50
157/157 [==============================] - 16s 102ms/step - loss: 4.8392e-05 - mae: 0.0044 - val_loss: 1.8416e-05 - val_mae: 0.0034
Epoch 20/50
157/157 [==============================] - 16s 101ms/step - loss: 4.6393e-05 - mae: 0.0043 - val_loss: 1.9444e-05 - val_mae: 0.0035
Epoch 21/50
157/157 [==============================] - 18s 117ms/step - loss: 4.0465e-05 - mae: 0.0041 - val_loss: 1.9030e-05 - val_mae: 0.0035
Epoch 22/50
157/157 [==============================] - 16s 102ms/step - loss: 4.0703e-05 - mae: 0.0041 - val_loss: 1.9478e-05 - val_mae: 0.0035
Epoch 23/50
157/157 [==============================] - 21s 134ms/step - loss: 3.6534e-05 - mae: 0.0040 - val_loss: 1.7702e-05 - val_mae: 0.0033
Epoch 24/50
157/157 [==============================] - 19s 121ms/step - loss: 3.8366e-05 - mae: 0.0040 - val_loss: 2.3340e-05 - val_mae: 0.0038
Epoch 25/50
157/157 [==============================] - 15s 98ms/step - loss: 4.4216e-05 - mae: 0.0042 - val_loss: 1.9925e-05 - val_mae: 0.0035
Epoch 26/50
157/157 [==============================] - 16s 101ms/step - loss: 3.8896e-05 - mae: 0.0040 - val_loss: 1.6506e-05 - val_mae: 0.0032
Epoch 27/50
157/157 [==============================] - 16s 101ms/step - loss: 3.7639e-05 - mae: 0.0040 - val_loss: 1.8209e-05 - val_mae: 0.0034
Epoch 28/50
157/157 [==============================] - 18s 115ms/step - loss: 3.8620e-05 - mae: 0.0039 - val_loss: 1.4404e-05 - val_mae: 0.0030
Epoch 29/50
157/157 [==============================] - 21s 131ms/step - loss: 3.5842e-05 - mae: 0.0038 - val_loss: 2.3068e-05 - val_mae: 0.0039
Epoch 30/50
157/157 [==============================] - 20s 126ms/step - loss: 3.6817e-05 - mae: 0.0039 - val_loss: 1.6802e-05 - val_mae: 0.0033
Epoch 31/50
157/157 [==============================] - 16s 102ms/step - loss: 3.7815e-05 - mae: 0.0039 - val_loss: 2.1610e-05 - val_mae: 0.0037
Epoch 32/50
157/157 [==============================] - 16s 101ms/step - loss: 3.3907e-05 - mae: 0.0038 - val_loss: 1.6559e-05 - val_mae: 0.0032
Epoch 33/50
157/157 [==============================] - 15s 98ms/step - loss: 3.4936e-05 - mae: 0.0038 - val_loss: 1.4804e-05 - val_mae: 0.0030
Epoch 34/50
157/157 [==============================] - 16s 101ms/step - loss: 3.1647e-05 - mae: 0.0037 - val_loss: 1.5049e-05 - val_mae: 0.0031
Epoch 35/50
157/157 [==============================] - 20s 126ms/step - loss: 3.1665e-05 - mae: 0.0037 - val_loss: 1.4567e-05 - val_mae: 0.0030
Epoch 36/50
157/157 [==============================] - 18s 116ms/step - loss: 3.7233e-05 - mae: 0.0037 - val_loss: 1.6640e-05 - val_mae: 0.0032
Epoch 37/50
157/157 [==============================] - 18s 117ms/step - loss: 3.3151e-05 - mae: 0.0038 - val_loss: 1.1962e-05 - val_mae: 0.0027
Epoch 38/50
157/157 [==============================] - 16s 102ms/step - loss: 3.1403e-05 - mae: 0.0036 - val_loss: 2.1903e-05 - val_mae: 0.0037
Epoch 39/50
157/157 [==============================] - 17s 108ms/step - loss: 3.1091e-05 - mae: 0.0036 - val_loss: 1.8344e-05 - val_mae: 0.0034
Epoch 40/50
157/157 [==============================] - 16s 99ms/step - loss: 3.3686e-05 - mae: 0.0037 - val_loss: 1.6480e-05 - val_mae: 0.0032
Epoch 41/50
157/157 [==============================] - 19s 118ms/step - loss: 3.1826e-05 - mae: 0.0037 - val_loss: 1.5492e-05 - val_mae: 0.0031
Epoch 42/50
157/157 [==============================] - 20s 126ms/step - loss: 3.6677e-05 - mae: 0.0037 - val_loss: 1.5941e-05 - val_mae: 0.0032
Epoch 43/50
157/157 [==============================] - 16s 102ms/step - loss: 3.0540e-05 - mae: 0.0036 - val_loss: 1.7956e-05 - val_mae: 0.0034
Epoch 44/50
157/157 [==============================] - 18s 116ms/step - loss: 3.1359e-05 - mae: 0.0036 - val_loss: 1.4757e-05 - val_mae: 0.0030
Epoch 45/50
157/157 [==============================] - 15s 98ms/step - loss: 3.1187e-05 - mae: 0.0035 - val_loss: 1.6626e-05 - val_mae: 0.0032
Epoch 46/50
157/157 [==============================] - 15s 98ms/step - loss: 3.0643e-05 - mae: 0.0035 - val_loss: 1.3092e-05 - val_mae: 0.0028
Epoch 47/50
157/157 [==============================] - 20s 130ms/step - loss: 3.4782e-05 - mae: 0.0037 - val_loss: 1.4063e-05 - val_mae: 0.0029
Epoch 48/50
157/157 [==============================] - 15s 99ms/step - loss: 2.9184e-05 - mae: 0.0036 - val_loss: 1.4411e-05 - val_mae: 0.0030
Epoch 49/50
157/157 [==============================] - 18s 117ms/step - loss: 3.2714e-05 - mae: 0.0036 - val_loss: 1.1717e-05 - val_mae: 0.0026
Epoch 50/50
157/157 [==============================] - 16s 101ms/step - loss: 3.1099e-05 - mae: 0.0036 - val_loss: 1.8680e-05 - val_mae: 0.0035
63/63 [==============================] - 3s 17ms/step

In [11]:


def prepare_data(filename):
    data = filename
    X = data.drop(columns=['A_M1_B1_W1_Z_L', 'A_M1_B1_BC_Z_L', 'A_M1_B1_W1_Z_R', 'A_M1_B1_BC_Z_R', 'A_M1_B1_W2_Z_R', 'A__B1_W1_Z_A_axle_L', 'A__B1_W1_Z_A_axle_R', 'A__B1_W2_Z_A_axle_R', 'V_M1_B1_W1_L', 'V_M1_B1_W1_R', 'QL_M1_B1_W1', 'QR_M1_B1_W1'])
    y = data[["YL_M1_B1_W2", "YR_M1_B1_W2"]]

    # 데이터 스케일링
    scaler_X = StandardScaler()
    X = scaler_X.fit_transform(X)

    # scaler_y = StandardScaler()  # y 데이터에 대한 새로운 스케일러
    # y = scaler_y.fit_transform(y)  # 2차원 배열로 변환

    return X, y

def reshape_data(X, y, N_TIMESTEPS):
    X_list, y_list = [], []
    X_padded = np.vstack([np.zeros((N_TIMESTEPS, X.shape[1])), X])

    for i in range(len(X_padded) - N_TIMESTEPS):
        X_list.append(X_padded[i:i+N_TIMESTEPS])
        y_list.append(y.iloc[i])

    return np.array(X_list), np.array(y_list)


data_s_X, data_s_y = prepare_data(c40_train)   #####################################################

N_TIMESTEPS = 10
N_FEATURES = 26

X_s, y_s = reshape_data(data_s_X, data_s_y, N_TIMESTEPS)

# 트레이닝/테스트 데이터 나누기
X_train_s = X_s[:10001]
y_train_s = y_s[:10001]
X_test_s = X_s[10001:]
y_test_s = y_s[10001:]


# Early stopping
es = EarlyStopping(monitor='val_loss', mode='min', verbose=1, patience=20)

from tensorflow.keras.layers import RepeatVector, TimeDistributed

# DeepAR 스타일의 모델 구축
inputs = tf.keras.Input(shape=(N_TIMESTEPS, N_FEATURES))

# LSTM을 통한 인코딩
x = LSTM(64, return_sequences=True)(inputs)
x = LSTM(128, return_sequences=False)(x)
x = Dropout(0.5)(x)

# 미래 타임스텝에 대한 예측을 위한 RepeatVector
x = RepeatVector(N_TIMESTEPS)(x)

# LSTM을 통한 디코딩
x = LSTM(128, return_sequences=True)(x)
x = LSTM(64, return_sequences=True)(x)
x = Dropout(0.5)(x)

# 각 타임스텝에 대한 출력 값 생성
x = TimeDistributed(Dense(2))(x)

model_deepar = Model(inputs=inputs, outputs=x[:, -1, :])  # 마지막 타임스텝의 출력만 사용

model_deepar.compile(optimizer=tf.keras.optimizers.Adam(learning_rate=0.001), loss='mse', metrics=['mae'])

model_deepar.fit(X_train_s, y_train_s, epochs=50, batch_size=64, validation_data=(X_test_s, y_test_s), callbacks=[es])


# 예측
predictions_s2 = model_deepar.predict(X_test_s)

Epoch 1/50
157/157 [==============================] - 32s 146ms/step - loss: 0.0013 - mae: 0.0244 - val_loss: 3.4312e-04 - val_mae: 0.0147
Epoch 2/50
157/157 [==============================] - 18s 113ms/step - loss: 3.4173e-04 - mae: 0.0136 - val_loss: 2.4246e-04 - val_mae: 0.0122
Epoch 3/50
157/157 [==============================] - 16s 100ms/step - loss: 2.4604e-04 - mae: 0.0113 - val_loss: 1.9047e-04 - val_mae: 0.0108
Epoch 4/50
157/157 [==============================] - 18s 112ms/step - loss: 2.1190e-04 - mae: 0.0104 - val_loss: 1.8276e-04 - val_mae: 0.0108
Epoch 5/50
157/157 [==============================] - 16s 102ms/step - loss: 1.7648e-04 - mae: 0.0096 - val_loss: 1.5243e-04 - val_mae: 0.0097
Epoch 6/50
157/157 [==============================] - 16s 102ms/step - loss: 1.6160e-04 - mae: 0.0092 - val_loss: 1.2092e-04 - val_mae: 0.0087
Epoch 7/50
157/157 [==============================] - 22s 141ms/step - loss: 1.5773e-04 - mae: 0.0089 - val_loss: 1.1614e-04 - val_mae: 0.0084
Epoch 8/50
157/157 [==============================] - 16s 101ms/step - loss: 1.4496e-04 - mae: 0.0086 - val_loss: 1.5003e-04 - val_mae: 0.0099
Epoch 9/50
157/157 [==============================] - 18s 114ms/step - loss: 1.4085e-04 - mae: 0.0084 - val_loss: 1.1335e-04 - val_mae: 0.0086
Epoch 10/50
157/157 [==============================] - 16s 102ms/step - loss: 1.2728e-04 - mae: 0.0081 - val_loss: 7.8401e-05 - val_mae: 0.0069
Epoch 11/50
157/157 [==============================] - 18s 118ms/step - loss: 1.2374e-04 - mae: 0.0079 - val_loss: 9.5494e-05 - val_mae: 0.0077
Epoch 12/50
157/157 [==============================] - 18s 118ms/step - loss: 1.2223e-04 - mae: 0.0077 - val_loss: 9.5890e-05 - val_mae: 0.0077
Epoch 13/50
157/157 [==============================] - 17s 110ms/step - loss: 1.2104e-04 - mae: 0.0077 - val_loss: 8.8859e-05 - val_mae: 0.0074
Epoch 14/50
157/157 [==============================] - 16s 101ms/step - loss: 1.1294e-04 - mae: 0.0074 - val_loss: 8.5682e-05 - val_mae: 0.0073
Epoch 15/50
157/157 [==============================] - 16s 100ms/step - loss: 1.1037e-04 - mae: 0.0073 - val_loss: 8.8347e-05 - val_mae: 0.0075
Epoch 16/50
157/157 [==============================] - 20s 125ms/step - loss: 1.0064e-04 - mae: 0.0070 - val_loss: 8.7020e-05 - val_mae: 0.0074
Epoch 17/50
157/157 [==============================] - 16s 102ms/step - loss: 9.6054e-05 - mae: 0.0068 - val_loss: 8.4332e-05 - val_mae: 0.0072
Epoch 18/50
157/157 [==============================] - 20s 127ms/step - loss: 9.3442e-05 - mae: 0.0067 - val_loss: 6.9126e-05 - val_mae: 0.0065
Epoch 19/50
157/157 [==============================] - 18s 116ms/step - loss: 9.7180e-05 - mae: 0.0068 - val_loss: 7.4967e-05 - val_mae: 0.0069
Epoch 20/50
157/157 [==============================] - 16s 101ms/step - loss: 9.5747e-05 - mae: 0.0067 - val_loss: 5.9669e-05 - val_mae: 0.0061
Epoch 21/50
157/157 [==============================] - 15s 99ms/step - loss: 8.8057e-05 - mae: 0.0065 - val_loss: 6.5230e-05 - val_mae: 0.0064
Epoch 22/50
157/157 [==============================] - 16s 102ms/step - loss: 8.7339e-05 - mae: 0.0064 - val_loss: 5.4068e-05 - val_mae: 0.0058
Epoch 23/50
157/157 [==============================] - 21s 134ms/step - loss: 8.7885e-05 - mae: 0.0064 - val_loss: 6.3116e-05 - val_mae: 0.0065
Epoch 24/50
157/157 [==============================] - 21s 133ms/step - loss: 8.6150e-05 - mae: 0.0064 - val_loss: 5.0441e-05 - val_mae: 0.0057
Epoch 25/50
157/157 [==============================] - 18s 114ms/step - loss: 8.8917e-05 - mae: 0.0064 - val_loss: 4.8627e-05 - val_mae: 0.0056
Epoch 26/50
157/157 [==============================] - 15s 98ms/step - loss: 8.3249e-05 - mae: 0.0062 - val_loss: 4.5787e-05 - val_mae: 0.0054
Epoch 27/50
157/157 [==============================] - 16s 101ms/step - loss: 8.6084e-05 - mae: 0.0062 - val_loss: 4.4668e-05 - val_mae: 0.0053
Epoch 28/50
157/157 [==============================] - 16s 102ms/step - loss: 8.7144e-05 - mae: 0.0063 - val_loss: 4.6171e-05 - val_mae: 0.0054
Epoch 29/50
157/157 [==============================] - 16s 103ms/step - loss: 8.0682e-05 - mae: 0.0061 - val_loss: 5.6971e-05 - val_mae: 0.0061
Epoch 30/50
157/157 [==============================] - 22s 143ms/step - loss: 7.9209e-05 - mae: 0.0061 - val_loss: 5.0774e-05 - val_mae: 0.0057
Epoch 31/50
157/157 [==============================] - 16s 102ms/step - loss: 7.2671e-05 - mae: 0.0059 - val_loss: 3.9476e-05 - val_mae: 0.0050
Epoch 32/50
157/157 [==============================] - 20s 125ms/step - loss: 8.3916e-05 - mae: 0.0061 - val_loss: 4.7569e-05 - val_mae: 0.0055
Epoch 33/50
157/157 [==============================] - 17s 109ms/step - loss: 8.3073e-05 - mae: 0.0061 - val_loss: 6.0014e-05 - val_mae: 0.0062
Epoch 34/50
157/157 [==============================] - 16s 101ms/step - loss: 7.8392e-05 - mae: 0.0060 - val_loss: 4.3434e-05 - val_mae: 0.0053
Epoch 35/50
157/157 [==============================] - 16s 101ms/step - loss: 7.7120e-05 - mae: 0.0059 - val_loss: 4.6743e-05 - val_mae: 0.0055
Epoch 36/50
157/157 [==============================] - 20s 128ms/step - loss: 8.1874e-05 - mae: 0.0061 - val_loss: 4.8192e-05 - val_mae: 0.0056
Epoch 37/50
157/157 [==============================] - 18s 117ms/step - loss: 7.5992e-05 - mae: 0.0059 - val_loss: 3.7006e-05 - val_mae: 0.0048
Epoch 38/50
157/157 [==============================] - 16s 102ms/step - loss: 7.2789e-05 - mae: 0.0059 - val_loss: 2.9510e-05 - val_mae: 0.0043
Epoch 39/50
157/157 [==============================] - 16s 102ms/step - loss: 8.3575e-05 - mae: 0.0061 - val_loss: 2.8306e-05 - val_mae: 0.0042
Epoch 40/50
157/157 [==============================] - 15s 99ms/step - loss: 8.0537e-05 - mae: 0.0060 - val_loss: 3.7114e-05 - val_mae: 0.0049
Epoch 41/50
157/157 [==============================] - 19s 122ms/step - loss: 7.5386e-05 - mae: 0.0059 - val_loss: 3.2604e-05 - val_mae: 0.0045
Epoch 42/50
157/157 [==============================] - 17s 106ms/step - loss: 7.8943e-05 - mae: 0.0060 - val_loss: 5.1869e-05 - val_mae: 0.0058
Epoch 43/50
157/157 [==============================] - 17s 108ms/step - loss: 7.6129e-05 - mae: 0.0059 - val_loss: 3.3837e-05 - val_mae: 0.0046
Epoch 44/50
157/157 [==============================] - 18s 115ms/step - loss: 7.2661e-05 - mae: 0.0059 - val_loss: 3.6915e-05 - val_mae: 0.0049
Epoch 45/50
157/157 [==============================] - 16s 99ms/step - loss: 7.5915e-05 - mae: 0.0058 - val_loss: 3.3337e-05 - val_mae: 0.0047
Epoch 46/50
157/157 [==============================] - 16s 102ms/step - loss: 8.6775e-05 - mae: 0.0062 - val_loss: 3.4302e-05 - val_mae: 0.0047
Epoch 47/50
157/157 [==============================] - 23s 144ms/step - loss: 7.3885e-05 - mae: 0.0058 - val_loss: 3.1300e-05 - val_mae: 0.0045
Epoch 48/50
157/157 [==============================] - 16s 101ms/step - loss: 7.1953e-05 - mae: 0.0057 - val_loss: 3.6164e-05 - val_mae: 0.0048
Epoch 49/50
157/157 [==============================] - 18s 112ms/step - loss: 7.6918e-05 - mae: 0.0059 - val_loss: 3.7505e-05 - val_mae: 0.0049
Epoch 50/50
157/157 [==============================] - 16s 99ms/step - loss: 7.4059e-05 - mae: 0.0057 - val_loss: 2.9307e-05 - val_mae: 0.0043
63/63 [==============================] - 3s 26ms/step

In [12]:
predictions_40c = pd.DataFrame(predictions_s, columns=['YL_M1_B1_W1', 'YR_M1_B1_W1'])
predictions_40c2 = pd.DataFrame(predictions_s2, columns=['YL_M1_B1_W2', 'YR_M1_B1_W2'])

In [13]:
def prepare_data(filename):
    data = filename
    X = data.drop(columns=['Curvature', 'Vertical offset', 'Cross level offset', 'A_M1_B1_W1_Z_L', 'A_M1_B1_BC_Z_L', 'A_M1_B1_W2_Z_L', 'A_M1_B1_W1_Z_R', 'A_M1_B1_BC_Z_R', 'A_M1_B1_W2_Z_R', 'A__B1_W2_Y_A_axle_L', 'A__B1_W1_Z_A_axle_R'])
    y = data[["YL_M1_B1_W1", "YR_M1_B1_W1"]]

    # 데이터 스케일링
    scaler_X = StandardScaler()
    X = scaler_X.fit_transform(X)

    # scaler_y = StandardScaler()  # y 데이터에 대한 새로운 스케일러
    # y = scaler_y.fit_transform(y)  # 2차원 배열로 변환

    return X, y

def reshape_data(X, y, N_TIMESTEPS):
    X_list, y_list = [], []
    X_padded = np.vstack([np.zeros((N_TIMESTEPS, X.shape[1])), X])

    for i in range(len(X_padded) - N_TIMESTEPS):
        X_list.append(X_padded[i:i+N_TIMESTEPS])
        y_list.append(y.iloc[i])

    return np.array(X_list), np.array(y_list)


data_s_X, data_s_y = prepare_data(c50_train)   #####################################################

N_TIMESTEPS = 10
N_FEATURES = 27

X_s, y_s = reshape_data(data_s_X, data_s_y, N_TIMESTEPS)

# 트레이닝/테스트 데이터 나누기
X_train_s = X_s[:10001]
y_train_s = y_s[:10001]
X_test_s = X_s[10001:]
y_test_s = y_s[10001:]


# Early stopping
es = EarlyStopping(monitor='val_loss', mode='min', verbose=1, patience=20)

from tensorflow.keras.layers import RepeatVector, TimeDistributed

# DeepAR 스타일의 모델 구축
inputs = tf.keras.Input(shape=(N_TIMESTEPS, N_FEATURES))

# LSTM을 통한 인코딩
x = LSTM(64, return_sequences=True)(inputs)
x = LSTM(128, return_sequences=False)(x)
x = Dropout(0.5)(x)

# 미래 타임스텝에 대한 예측을 위한 RepeatVector
x = RepeatVector(N_TIMESTEPS)(x)

# LSTM을 통한 디코딩
x = LSTM(128, return_sequences=True)(x)
x = LSTM(64, return_sequences=True)(x)
x = Dropout(0.5)(x)

# 각 타임스텝에 대한 출력 값 생성
x = TimeDistributed(Dense(2))(x)

model_deepar = Model(inputs=inputs, outputs=x[:, -1, :])  # 마지막 타임스텝의 출력만 사용

model_deepar.compile(optimizer=tf.keras.optimizers.Adam(learning_rate=0.001), loss='mse', metrics=['mae'])

model_deepar.fit(X_train_s, y_train_s, epochs=50, batch_size=64, validation_data=(X_test_s, y_test_s), callbacks=[es])


# 예측
predictions_s = model_deepar.predict(X_test_s)

Epoch 1/50
157/157 [==============================] - 28s 121ms/step - loss: 9.0843e-04 - mae: 0.0202 - val_loss: 8.2063e-05 - val_mae: 0.0072
Epoch 2/50
157/157 [==============================] - 16s 101ms/step - loss: 1.7350e-04 - mae: 0.0099 - val_loss: 8.7950e-05 - val_mae: 0.0075
Epoch 3/50
157/157 [==============================] - 16s 103ms/step - loss: 1.2229e-04 - mae: 0.0082 - val_loss: 7.7037e-05 - val_mae: 0.0069
Epoch 4/50
157/157 [==============================] - 16s 103ms/step - loss: 9.7989e-05 - mae: 0.0073 - val_loss: 7.1470e-05 - val_mae: 0.0066
Epoch 5/50
157/157 [==============================] - 18s 117ms/step - loss: 8.6039e-05 - mae: 0.0069 - val_loss: 5.2259e-05 - val_mae: 0.0057
Epoch 6/50
157/157 [==============================] - 20s 130ms/step - loss: 8.0779e-05 - mae: 0.0066 - val_loss: 4.9592e-05 - val_mae: 0.0055
Epoch 7/50
157/157 [==============================] - 19s 118ms/step - loss: 7.3711e-05 - mae: 0.0062 - val_loss: 4.7691e-05 - val_mae: 0.0054
Epoch 8/50
157/157 [==============================] - 16s 103ms/step - loss: 6.6965e-05 - mae: 0.0060 - val_loss: 4.3772e-05 - val_mae: 0.0053
Epoch 9/50
157/157 [==============================] - 16s 105ms/step - loss: 6.0208e-05 - mae: 0.0057 - val_loss: 3.5867e-05 - val_mae: 0.0047
Epoch 10/50
157/157 [==============================] - 18s 113ms/step - loss: 5.5333e-05 - mae: 0.0055 - val_loss: 3.8929e-05 - val_mae: 0.0049
Epoch 11/50
157/157 [==============================] - 19s 122ms/step - loss: 5.0751e-05 - mae: 0.0053 - val_loss: 3.2782e-05 - val_mae: 0.0045
Epoch 12/50
157/157 [==============================] - 20s 127ms/step - loss: 4.7924e-05 - mae: 0.0051 - val_loss: 3.2375e-05 - val_mae: 0.0044
Epoch 13/50
157/157 [==============================] - 17s 111ms/step - loss: 4.5592e-05 - mae: 0.0049 - val_loss: 2.6726e-05 - val_mae: 0.0040
Epoch 14/50
157/157 [==============================] - 22s 143ms/step - loss: 4.1502e-05 - mae: 0.0047 - val_loss: 3.0024e-05 - val_mae: 0.0043
Epoch 15/50
157/157 [==============================] - 18s 114ms/step - loss: 4.1849e-05 - mae: 0.0046 - val_loss: 2.7847e-05 - val_mae: 0.0041
Epoch 16/50
157/157 [==============================] - 18s 116ms/step - loss: 4.2484e-05 - mae: 0.0046 - val_loss: 2.5332e-05 - val_mae: 0.0040
Epoch 17/50
157/157 [==============================] - 24s 154ms/step - loss: 3.6162e-05 - mae: 0.0044 - val_loss: 2.5723e-05 - val_mae: 0.0040
Epoch 18/50
157/157 [==============================] - 22s 137ms/step - loss: 3.7236e-05 - mae: 0.0043 - val_loss: 2.8060e-05 - val_mae: 0.0041
Epoch 19/50
157/157 [==============================] - 18s 115ms/step - loss: 3.5090e-05 - mae: 0.0042 - val_loss: 2.4021e-05 - val_mae: 0.0039
Epoch 20/50
157/157 [==============================] - 20s 130ms/step - loss: 3.4895e-05 - mae: 0.0042 - val_loss: 2.2945e-05 - val_mae: 0.0038
Epoch 21/50
157/157 [==============================] - 19s 123ms/step - loss: 3.3144e-05 - mae: 0.0041 - val_loss: 2.5906e-05 - val_mae: 0.0041
Epoch 22/50
157/157 [==============================] - 21s 135ms/step - loss: 2.9907e-05 - mae: 0.0039 - val_loss: 2.3609e-05 - val_mae: 0.0039
Epoch 23/50
157/157 [==============================] - 17s 107ms/step - loss: 3.1569e-05 - mae: 0.0040 - val_loss: 2.5519e-05 - val_mae: 0.0041
Epoch 24/50
157/157 [==============================] - 21s 133ms/step - loss: 3.0038e-05 - mae: 0.0039 - val_loss: 1.7441e-05 - val_mae: 0.0033
Epoch 25/50
157/157 [==============================] - 18s 116ms/step - loss: 2.8493e-05 - mae: 0.0038 - val_loss: 1.8385e-05 - val_mae: 0.0034
Epoch 26/50
157/157 [==============================] - 17s 106ms/step - loss: 2.8827e-05 - mae: 0.0038 - val_loss: 1.8205e-05 - val_mae: 0.0034
Epoch 27/50
157/157 [==============================] - 23s 146ms/step - loss: 3.0069e-05 - mae: 0.0038 - val_loss: 2.3541e-05 - val_mae: 0.0039
Epoch 28/50
157/157 [==============================] - 16s 105ms/step - loss: 2.7608e-05 - mae: 0.0037 - val_loss: 2.2024e-05 - val_mae: 0.0037
Epoch 29/50
157/157 [==============================] - 17s 105ms/step - loss: 2.8824e-05 - mae: 0.0037 - val_loss: 2.0955e-05 - val_mae: 0.0037
Epoch 30/50
157/157 [==============================] - 16s 104ms/step - loss: 2.8715e-05 - mae: 0.0037 - val_loss: 1.8544e-05 - val_mae: 0.0034
Epoch 31/50
157/157 [==============================] - 19s 119ms/step - loss: 2.7522e-05 - mae: 0.0036 - val_loss: 1.7976e-05 - val_mae: 0.0034
Epoch 32/50
157/157 [==============================] - 16s 103ms/step - loss: 2.6917e-05 - mae: 0.0036 - val_loss: 1.7446e-05 - val_mae: 0.0034
Epoch 33/50
157/157 [==============================] - 22s 141ms/step - loss: 2.5723e-05 - mae: 0.0036 - val_loss: 1.7991e-05 - val_mae: 0.0034
Epoch 34/50
157/157 [==============================] - 16s 104ms/step - loss: 2.4235e-05 - mae: 0.0035 - val_loss: 1.5524e-05 - val_mae: 0.0031
Epoch 35/50
157/157 [==============================] - 16s 103ms/step - loss: 3.2535e-05 - mae: 0.0039 - val_loss: 1.7704e-05 - val_mae: 0.0033
Epoch 36/50
157/157 [==============================] - 16s 103ms/step - loss: 2.9120e-05 - mae: 0.0037 - val_loss: 1.8589e-05 - val_mae: 0.0034
Epoch 37/50
157/157 [==============================] - 16s 103ms/step - loss: 3.0018e-05 - mae: 0.0037 - val_loss: 1.6526e-05 - val_mae: 0.0032
Epoch 38/50
157/157 [==============================] - 20s 129ms/step - loss: 2.6519e-05 - mae: 0.0036 - val_loss: 1.3354e-05 - val_mae: 0.0029
Epoch 39/50
157/157 [==============================] - 20s 131ms/step - loss: 2.5058e-05 - mae: 0.0035 - val_loss: 2.0741e-05 - val_mae: 0.0037
Epoch 40/50
157/157 [==============================] - 16s 104ms/step - loss: 2.3897e-05 - mae: 0.0034 - val_loss: 1.4859e-05 - val_mae: 0.0031
Epoch 41/50
157/157 [==============================] - 18s 115ms/step - loss: 2.6319e-05 - mae: 0.0036 - val_loss: 1.4786e-05 - val_mae: 0.0031
Epoch 42/50
157/157 [==============================] - 16s 100ms/step - loss: 2.6184e-05 - mae: 0.0035 - val_loss: 1.2518e-05 - val_mae: 0.0028
Epoch 43/50
157/157 [==============================] - 16s 103ms/step - loss: 2.3278e-05 - mae: 0.0034 - val_loss: 1.7574e-05 - val_mae: 0.0033
Epoch 44/50
157/157 [==============================] - 16s 103ms/step - loss: 2.1536e-05 - mae: 0.0033 - val_loss: 1.4115e-05 - val_mae: 0.0030
Epoch 45/50
157/157 [==============================] - 25s 157ms/step - loss: 2.2567e-05 - mae: 0.0033 - val_loss: 1.7383e-05 - val_mae: 0.0033
Epoch 46/50
157/157 [==============================] - 17s 105ms/step - loss: 2.1481e-05 - mae: 0.0033 - val_loss: 1.6037e-05 - val_mae: 0.0032
Epoch 47/50
157/157 [==============================] - 16s 100ms/step - loss: 2.3794e-05 - mae: 0.0033 - val_loss: 1.4303e-05 - val_mae: 0.0030
Epoch 48/50
157/157 [==============================] - 18s 115ms/step - loss: 2.1260e-05 - mae: 0.0033 - val_loss: 1.3756e-05 - val_mae: 0.0029
Epoch 49/50
157/157 [==============================] - 16s 104ms/step - loss: 2.3648e-05 - mae: 0.0034 - val_loss: 1.4478e-05 - val_mae: 0.0030
Epoch 50/50
157/157 [==============================] - 16s 104ms/step - loss: 2.4355e-05 - mae: 0.0034 - val_loss: 1.6925e-05 - val_mae: 0.0033
63/63 [==============================] - 4s 31ms/step

In [14]:


def prepare_data(filename):
    data = filename
    X = data.drop(columns=['A_M1_B1_W1_Z_L', 'A_M1_B1_BC_Z_L', 'A_M1_B1_W1_Z_R', 'A_M1_B1_BC_Z_R', 'A_M1_B1_W2_Z_R', 'A__B1_W1_Z_A_axle_L', 'A__B1_W1_Z_A_axle_R', 'A__B1_W2_Z_A_axle_R', 'V_M1_B1_W1_L', 'V_M1_B1_W1_R', 'QL_M1_B1_W1', 'QR_M1_B1_W1'])
    y = data[["YL_M1_B1_W2", "YR_M1_B1_W2"]]

    # 데이터 스케일링
    scaler_X = StandardScaler()
    X = scaler_X.fit_transform(X)

    # scaler_y = StandardScaler()  # y 데이터에 대한 새로운 스케일러
    # y = scaler_y.fit_transform(y)  # 2차원 배열로 변환

    return X, y

def reshape_data(X, y, N_TIMESTEPS):
    X_list, y_list = [], []
    X_padded = np.vstack([np.zeros((N_TIMESTEPS, X.shape[1])), X])

    for i in range(len(X_padded) - N_TIMESTEPS):
        X_list.append(X_padded[i:i+N_TIMESTEPS])
        y_list.append(y.iloc[i])

    return np.array(X_list), np.array(y_list)


data_s_X, data_s_y = prepare_data(c50_train)   #####################################################

N_TIMESTEPS = 10
N_FEATURES = 26

X_s, y_s = reshape_data(data_s_X, data_s_y, N_TIMESTEPS)

# 트레이닝/테스트 데이터 나누기
X_train_s = X_s[:10001]
y_train_s = y_s[:10001]
X_test_s = X_s[10001:]
y_test_s = y_s[10001:]


# Early stopping
es = EarlyStopping(monitor='val_loss', mode='min', verbose=1, patience=20)

from tensorflow.keras.layers import RepeatVector, TimeDistributed

# DeepAR 스타일의 모델 구축
inputs = tf.keras.Input(shape=(N_TIMESTEPS, N_FEATURES))

# LSTM을 통한 인코딩
x = LSTM(64, return_sequences=True)(inputs)
x = LSTM(128, return_sequences=False)(x)
x = Dropout(0.5)(x)

# 미래 타임스텝에 대한 예측을 위한 RepeatVector
x = RepeatVector(N_TIMESTEPS)(x)

# LSTM을 통한 디코딩
x = LSTM(128, return_sequences=True)(x)
x = LSTM(64, return_sequences=True)(x)
x = Dropout(0.5)(x)

# 각 타임스텝에 대한 출력 값 생성
x = TimeDistributed(Dense(2))(x)

model_deepar = Model(inputs=inputs, outputs=x[:, -1, :])  # 마지막 타임스텝의 출력만 사용

model_deepar.compile(optimizer=tf.keras.optimizers.Adam(learning_rate=0.001), loss='mse', metrics=['mae'])

model_deepar.fit(X_train_s, y_train_s, epochs=50, batch_size=64, validation_data=(X_test_s, y_test_s), callbacks=[es])


# 예측
predictions_s2 = model_deepar.predict(X_test_s)

Epoch 1/50
157/157 [==============================] - 28s 125ms/step - loss: 0.0012 - mae: 0.0240 - val_loss: 4.3040e-04 - val_mae: 0.0163
Epoch 2/50
157/157 [==============================] - 16s 101ms/step - loss: 2.9819e-04 - mae: 0.0130 - val_loss: 3.2823e-04 - val_mae: 0.0141
Epoch 3/50
157/157 [==============================] - 15s 96ms/step - loss: 2.2524e-04 - mae: 0.0111 - val_loss: 2.4540e-04 - val_mae: 0.0124
Epoch 4/50
157/157 [==============================] - 17s 111ms/step - loss: 1.8032e-04 - mae: 0.0098 - val_loss: 1.8491e-04 - val_mae: 0.0106
Epoch 5/50
157/157 [==============================] - 16s 100ms/step - loss: 1.6398e-04 - mae: 0.0094 - val_loss: 1.9183e-04 - val_mae: 0.0111
Epoch 6/50
157/157 [==============================] - 20s 127ms/step - loss: 1.4702e-04 - mae: 0.0089 - val_loss: 1.4801e-04 - val_mae: 0.0096
Epoch 7/50
157/157 [==============================] - 16s 100ms/step - loss: 1.3228e-04 - mae: 0.0084 - val_loss: 1.0856e-04 - val_mae: 0.0082
Epoch 8/50
157/157 [==============================] - 19s 124ms/step - loss: 1.2696e-04 - mae: 0.0082 - val_loss: 1.2855e-04 - val_mae: 0.0091
Epoch 9/50
157/157 [==============================] - 17s 105ms/step - loss: 1.1395e-04 - mae: 0.0077 - val_loss: 1.5990e-04 - val_mae: 0.0103
Epoch 10/50
157/157 [==============================] - 16s 100ms/step - loss: 1.1092e-04 - mae: 0.0076 - val_loss: 8.1622e-05 - val_mae: 0.0072
Epoch 11/50
157/157 [==============================] - 18s 114ms/step - loss: 1.0726e-04 - mae: 0.0075 - val_loss: 1.0952e-04 - val_mae: 0.0084
Epoch 12/50
157/157 [==============================] - 20s 129ms/step - loss: 9.6376e-05 - mae: 0.0071 - val_loss: 8.5036e-05 - val_mae: 0.0075
Epoch 13/50
157/157 [==============================] - 16s 102ms/step - loss: 9.7768e-05 - mae: 0.0071 - val_loss: 7.5294e-05 - val_mae: 0.0069
Epoch 14/50
157/157 [==============================] - 16s 103ms/step - loss: 9.0799e-05 - mae: 0.0068 - val_loss: 8.7953e-05 - val_mae: 0.0077
Epoch 15/50
157/157 [==============================] - 19s 123ms/step - loss: 8.7594e-05 - mae: 0.0067 - val_loss: 1.0017e-04 - val_mae: 0.0082
Epoch 16/50
157/157 [==============================] - 17s 109ms/step - loss: 8.4902e-05 - mae: 0.0066 - val_loss: 6.9208e-05 - val_mae: 0.0065
Epoch 17/50
157/157 [==============================] - 17s 107ms/step - loss: 8.3450e-05 - mae: 0.0065 - val_loss: 7.3407e-05 - val_mae: 0.0067
Epoch 18/50
157/157 [==============================] - 21s 134ms/step - loss: 8.0956e-05 - mae: 0.0064 - val_loss: 6.9389e-05 - val_mae: 0.0068
Epoch 19/50
157/157 [==============================] - 16s 102ms/step - loss: 7.8954e-05 - mae: 0.0062 - val_loss: 6.1288e-05 - val_mae: 0.0062
Epoch 20/50
157/157 [==============================] - 15s 97ms/step - loss: 7.7692e-05 - mae: 0.0062 - val_loss: 7.8283e-05 - val_mae: 0.0073
Epoch 21/50
157/157 [==============================] - 16s 100ms/step - loss: 7.6743e-05 - mae: 0.0062 - val_loss: 5.6489e-05 - val_mae: 0.0059
Epoch 22/50
157/157 [==============================] - 16s 100ms/step - loss: 7.3587e-05 - mae: 0.0061 - val_loss: 5.4214e-05 - val_mae: 0.0058
Epoch 23/50
157/157 [==============================] - 18s 115ms/step - loss: 7.0957e-05 - mae: 0.0059 - val_loss: 4.6444e-05 - val_mae: 0.0054
Epoch 24/50
157/157 [==============================] - 20s 129ms/step - loss: 6.6583e-05 - mae: 0.0058 - val_loss: 5.8902e-05 - val_mae: 0.0062
Epoch 25/50
157/157 [==============================] - 16s 100ms/step - loss: 6.9810e-05 - mae: 0.0059 - val_loss: 5.4602e-05 - val_mae: 0.0059
Epoch 26/50
157/157 [==============================] - 17s 109ms/step - loss: 7.3144e-05 - mae: 0.0060 - val_loss: 4.9652e-05 - val_mae: 0.0056
Epoch 27/50
157/157 [==============================] - 15s 98ms/step - loss: 6.7685e-05 - mae: 0.0057 - val_loss: 4.7296e-05 - val_mae: 0.0056
Epoch 28/50
157/157 [==============================] - 16s 102ms/step - loss: 7.0032e-05 - mae: 0.0059 - val_loss: 3.6901e-05 - val_mae: 0.0048
Epoch 29/50
157/157 [==============================] - 16s 99ms/step - loss: 6.6775e-05 - mae: 0.0057 - val_loss: 3.7672e-05 - val_mae: 0.0049
Epoch 30/50
157/157 [==============================] - 19s 122ms/step - loss: 6.6654e-05 - mae: 0.0057 - val_loss: 4.0181e-05 - val_mae: 0.0051
Epoch 31/50
157/157 [==============================] - 20s 129ms/step - loss: 6.6170e-05 - mae: 0.0056 - val_loss: 4.2911e-05 - val_mae: 0.0053
Epoch 32/50
157/157 [==============================] - 15s 98ms/step - loss: 6.6201e-05 - mae: 0.0057 - val_loss: 5.0820e-05 - val_mae: 0.0058
Epoch 33/50
157/157 [==============================] - 18s 116ms/step - loss: 6.4167e-05 - mae: 0.0056 - val_loss: 3.8599e-05 - val_mae: 0.0049
Epoch 34/50
157/157 [==============================] - 16s 100ms/step - loss: 6.5952e-05 - mae: 0.0056 - val_loss: 4.1842e-05 - val_mae: 0.0052
Epoch 35/50
157/157 [==============================] - 15s 98ms/step - loss: 6.5726e-05 - mae: 0.0056 - val_loss: 3.2114e-05 - val_mae: 0.0046
Epoch 36/50
157/157 [==============================] - 16s 100ms/step - loss: 6.3421e-05 - mae: 0.0056 - val_loss: 3.9055e-05 - val_mae: 0.0049
Epoch 37/50
157/157 [==============================] - 20s 128ms/step - loss: 6.6400e-05 - mae: 0.0056 - val_loss: 4.1031e-05 - val_mae: 0.0051
Epoch 38/50
157/157 [==============================] - 17s 105ms/step - loss: 6.4165e-05 - mae: 0.0055 - val_loss: 2.9033e-05 - val_mae: 0.0043
Epoch 39/50
157/157 [==============================] - 16s 99ms/step - loss: 5.9299e-05 - mae: 0.0054 - val_loss: 3.7356e-05 - val_mae: 0.0049
Epoch 40/50
157/157 [==============================] - 16s 104ms/step - loss: 6.4513e-05 - mae: 0.0055 - val_loss: 3.8883e-05 - val_mae: 0.0051
Epoch 41/50
157/157 [==============================] - 17s 105ms/step - loss: 5.8351e-05 - mae: 0.0053 - val_loss: 3.9063e-05 - val_mae: 0.0050
Epoch 42/50
157/157 [==============================] - 16s 100ms/step - loss: 5.9733e-05 - mae: 0.0054 - val_loss: 3.6427e-05 - val_mae: 0.0048
Epoch 43/50
157/157 [==============================] - 22s 142ms/step - loss: 6.0635e-05 - mae: 0.0054 - val_loss: 4.0950e-05 - val_mae: 0.0051
Epoch 44/50
157/157 [==============================] - 16s 100ms/step - loss: 5.9215e-05 - mae: 0.0054 - val_loss: 3.2956e-05 - val_mae: 0.0045
Epoch 45/50
157/157 [==============================] - 18s 115ms/step - loss: 6.0915e-05 - mae: 0.0054 - val_loss: 2.9442e-05 - val_mae: 0.0043
Epoch 46/50
157/157 [==============================] - 16s 100ms/step - loss: 6.1347e-05 - mae: 0.0055 - val_loss: 3.0143e-05 - val_mae: 0.0043
Epoch 47/50
157/157 [==============================] - 16s 101ms/step - loss: 5.8650e-05 - mae: 0.0053 - val_loss: 2.9683e-05 - val_mae: 0.0044
Epoch 48/50
157/157 [==============================] - 18s 117ms/step - loss: 5.8115e-05 - mae: 0.0053 - val_loss: 2.4450e-05 - val_mae: 0.0040
Epoch 49/50
157/157 [==============================] - 23s 147ms/step - loss: 5.8655e-05 - mae: 0.0053 - val_loss: 2.2552e-05 - val_mae: 0.0038
Epoch 50/50
157/157 [==============================] - 17s 105ms/step - loss: 5.8569e-05 - mae: 0.0054 - val_loss: 2.7485e-05 - val_mae: 0.0042
63/63 [==============================] - 5s 34ms/step

In [15]:
predictions_50c = pd.DataFrame(predictions_s, columns=['YL_M1_B1_W1', 'YR_M1_B1_W1'])
predictions_50c2 = pd.DataFrame(predictions_s2, columns=['YL_M1_B1_W2', 'YR_M1_B1_W2'])

In [16]:
def prepare_data(filename):
    data = filename
    X = data.drop(columns=['Curvature', 'Vertical offset', 'Cross level offset', 'A_M1_B1_W1_Z_L', 'A_M1_B1_BC_Z_L', 'A_M1_B1_W2_Z_L', 'A_M1_B1_W1_Z_R', 'A_M1_B1_BC_Z_R', 'A_M1_B1_W2_Z_R', 'A__B1_W2_Y_A_axle_L', 'A__B1_W1_Z_A_axle_R'])
    y = data[["YL_M1_B1_W1", "YR_M1_B1_W1"]]

    # 데이터 스케일링
    scaler_X = StandardScaler()
    X = scaler_X.fit_transform(X)

    # scaler_y = StandardScaler()  # y 데이터에 대한 새로운 스케일러
    # y = scaler_y.fit_transform(y)  # 2차원 배열로 변환

    return X, y

def reshape_data(X, y, N_TIMESTEPS):
    X_list, y_list = [], []
    X_padded = np.vstack([np.zeros((N_TIMESTEPS, X.shape[1])), X])

    for i in range(len(X_padded) - N_TIMESTEPS):
        X_list.append(X_padded[i:i+N_TIMESTEPS])
        y_list.append(y.iloc[i])

    return np.array(X_list), np.array(y_list)


data_s_X, data_s_y = prepare_data(c70_train)   #####################################################

N_TIMESTEPS = 10
N_FEATURES = 27

X_s, y_s = reshape_data(data_s_X, data_s_y, N_TIMESTEPS)

# 트레이닝/테스트 데이터 나누기
X_train_s = X_s[:10001]
y_train_s = y_s[:10001]
X_test_s = X_s[10001:]
y_test_s = y_s[10001:]


# Early stopping
es = EarlyStopping(monitor='val_loss', mode='min', verbose=1, patience=20)

from tensorflow.keras.layers import RepeatVector, TimeDistributed

# DeepAR 스타일의 모델 구축
inputs = tf.keras.Input(shape=(N_TIMESTEPS, N_FEATURES))

# LSTM을 통한 인코딩
x = LSTM(64, return_sequences=True)(inputs)
x = LSTM(128, return_sequences=False)(x)
x = Dropout(0.5)(x)

# 미래 타임스텝에 대한 예측을 위한 RepeatVector
x = RepeatVector(N_TIMESTEPS)(x)

# LSTM을 통한 디코딩
x = LSTM(128, return_sequences=True)(x)
x = LSTM(64, return_sequences=True)(x)
x = Dropout(0.5)(x)

# 각 타임스텝에 대한 출력 값 생성
x = TimeDistributed(Dense(2))(x)

model_deepar = Model(inputs=inputs, outputs=x[:, -1, :])  # 마지막 타임스텝의 출력만 사용

model_deepar.compile(optimizer=tf.keras.optimizers.Adam(learning_rate=0.001), loss='mse', metrics=['mae'])

model_deepar.fit(X_train_s, y_train_s, epochs=50, batch_size=64, validation_data=(X_test_s, y_test_s), callbacks=[es])


# 예측
predictions_s = model_deepar.predict(X_test_s)

Epoch 1/50
157/157 [==============================] - 33s 144ms/step - loss: 8.3017e-04 - mae: 0.0195 - val_loss: 7.5258e-05 - val_mae: 0.0069
Epoch 2/50
157/157 [==============================] - 16s 102ms/step - loss: 1.5607e-04 - mae: 0.0096 - val_loss: 7.4575e-05 - val_mae: 0.0068
Epoch 3/50
157/157 [==============================] - 16s 103ms/step - loss: 1.0919e-04 - mae: 0.0079 - val_loss: 7.1663e-05 - val_mae: 0.0067
Epoch 4/50
157/157 [==============================] - 16s 100ms/step - loss: 8.5490e-05 - mae: 0.0071 - val_loss: 5.8732e-05 - val_mae: 0.0060
Epoch 5/50
157/157 [==============================] - 19s 118ms/step - loss: 7.6431e-05 - mae: 0.0066 - val_loss: 7.2803e-05 - val_mae: 0.0067
Epoch 6/50
157/157 [==============================] - 16s 103ms/step - loss: 6.7718e-05 - mae: 0.0062 - val_loss: 4.9917e-05 - val_mae: 0.0055
Epoch 7/50
157/157 [==============================] - 20s 129ms/step - loss: 6.2326e-05 - mae: 0.0059 - val_loss: 5.0438e-05 - val_mae: 0.0055
Epoch 8/50
157/157 [==============================] - 21s 134ms/step - loss: 5.6365e-05 - mae: 0.0056 - val_loss: 4.0391e-05 - val_mae: 0.0050
Epoch 9/50
157/157 [==============================] - 16s 103ms/step - loss: 5.0093e-05 - mae: 0.0053 - val_loss: 4.5598e-05 - val_mae: 0.0053
Epoch 10/50
157/157 [==============================] - 16s 99ms/step - loss: 4.7154e-05 - mae: 0.0052 - val_loss: 4.4602e-05 - val_mae: 0.0053
Epoch 11/50
157/157 [==============================] - 15s 99ms/step - loss: 4.3573e-05 - mae: 0.0049 - val_loss: 3.8200e-05 - val_mae: 0.0049
Epoch 12/50
157/157 [==============================] - 19s 119ms/step - loss: 4.0017e-05 - mae: 0.0047 - val_loss: 3.9248e-05 - val_mae: 0.0049
Epoch 13/50
157/157 [==============================] - 20s 131ms/step - loss: 3.8227e-05 - mae: 0.0046 - val_loss: 3.4422e-05 - val_mae: 0.0046
Epoch 14/50
157/157 [==============================] - 16s 102ms/step - loss: 3.5883e-05 - mae: 0.0044 - val_loss: 3.0575e-05 - val_mae: 0.0044
Epoch 15/50
157/157 [==============================] - 16s 103ms/step - loss: 3.5398e-05 - mae: 0.0044 - val_loss: 2.1965e-05 - val_mae: 0.0037
Epoch 16/50
157/157 [==============================] - 18s 115ms/step - loss: 3.1909e-05 - mae: 0.0042 - val_loss: 2.3829e-05 - val_mae: 0.0038
Epoch 17/50
157/157 [==============================] - 16s 102ms/step - loss: 2.9992e-05 - mae: 0.0041 - val_loss: 2.8961e-05 - val_mae: 0.0042
Epoch 18/50
157/157 [==============================] - 17s 109ms/step - loss: 2.8793e-05 - mae: 0.0039 - val_loss: 2.2243e-05 - val_mae: 0.0037
Epoch 19/50
157/157 [==============================] - 17s 105ms/step - loss: 2.8730e-05 - mae: 0.0039 - val_loss: 2.3345e-05 - val_mae: 0.0038
Epoch 20/50
157/157 [==============================] - 22s 141ms/step - loss: 2.7496e-05 - mae: 0.0038 - val_loss: 2.7992e-05 - val_mae: 0.0042
Epoch 21/50
157/157 [==============================] - 16s 103ms/step - loss: 2.6367e-05 - mae: 0.0038 - val_loss: 2.3876e-05 - val_mae: 0.0039
Epoch 22/50
157/157 [==============================] - 20s 125ms/step - loss: 2.6530e-05 - mae: 0.0038 - val_loss: 1.9559e-05 - val_mae: 0.0035
Epoch 23/50
157/157 [==============================] - 18s 117ms/step - loss: 2.6264e-05 - mae: 0.0037 - val_loss: 2.0702e-05 - val_mae: 0.0036
Epoch 24/50
157/157 [==============================] - 16s 103ms/step - loss: 2.5294e-05 - mae: 0.0037 - val_loss: 2.1351e-05 - val_mae: 0.0036
Epoch 25/50
157/157 [==============================] - 21s 131ms/step - loss: 2.5863e-05 - mae: 0.0037 - val_loss: 1.6390e-05 - val_mae: 0.0032
Epoch 26/50
157/157 [==============================] - 18s 116ms/step - loss: 2.4760e-05 - mae: 0.0036 - val_loss: 2.2010e-05 - val_mae: 0.0037
Epoch 27/50
157/157 [==============================] - 17s 110ms/step - loss: 2.4392e-05 - mae: 0.0036 - val_loss: 2.1655e-05 - val_mae: 0.0037
Epoch 28/50
157/157 [==============================] - 16s 105ms/step - loss: 2.2437e-05 - mae: 0.0035 - val_loss: 2.1239e-05 - val_mae: 0.0037
Epoch 29/50
157/157 [==============================] - 16s 104ms/step - loss: 2.2076e-05 - mae: 0.0034 - val_loss: 2.2922e-05 - val_mae: 0.0038
Epoch 30/50
157/157 [==============================] - 18s 118ms/step - loss: 3.0240e-05 - mae: 0.0039 - val_loss: 2.5577e-05 - val_mae: 0.0040
Epoch 31/50
157/157 [==============================] - 21s 135ms/step - loss: 2.5440e-05 - mae: 0.0037 - val_loss: 1.9096e-05 - val_mae: 0.0035
Epoch 32/50
157/157 [==============================] - 17s 111ms/step - loss: 2.3763e-05 - mae: 0.0035 - val_loss: 2.0297e-05 - val_mae: 0.0036
Epoch 33/50
157/157 [==============================] - 17s 107ms/step - loss: 2.2747e-05 - mae: 0.0035 - val_loss: 1.7849e-05 - val_mae: 0.0033
Epoch 34/50
157/157 [==============================] - 18s 113ms/step - loss: 2.2122e-05 - mae: 0.0034 - val_loss: 1.6951e-05 - val_mae: 0.0033
Epoch 35/50
157/157 [==============================] - 16s 103ms/step - loss: 2.1696e-05 - mae: 0.0034 - val_loss: 1.4186e-05 - val_mae: 0.0030
Epoch 36/50
157/157 [==============================] - 16s 104ms/step - loss: 2.2307e-05 - mae: 0.0034 - val_loss: 1.9705e-05 - val_mae: 0.0035
Epoch 37/50
157/157 [==============================] - 21s 134ms/step - loss: 2.1425e-05 - mae: 0.0034 - val_loss: 1.6331e-05 - val_mae: 0.0032
Epoch 38/50
157/157 [==============================] - 17s 111ms/step - loss: 2.1616e-05 - mae: 0.0033 - val_loss: 1.6282e-05 - val_mae: 0.0032
Epoch 39/50
157/157 [==============================] - 16s 104ms/step - loss: 2.0325e-05 - mae: 0.0033 - val_loss: 1.4592e-05 - val_mae: 0.0030
Epoch 40/50
157/157 [==============================] - 17s 111ms/step - loss: 1.9840e-05 - mae: 0.0032 - val_loss: 1.8103e-05 - val_mae: 0.0033
Epoch 41/50
157/157 [==============================] - 19s 121ms/step - loss: 2.0492e-05 - mae: 0.0033 - val_loss: 1.7732e-05 - val_mae: 0.0033
Epoch 42/50
157/157 [==============================] - 16s 103ms/step - loss: 2.0520e-05 - mae: 0.0032 - val_loss: 2.0232e-05 - val_mae: 0.0036
Epoch 43/50
157/157 [==============================] - 18s 117ms/step - loss: 2.1062e-05 - mae: 0.0033 - val_loss: 1.3412e-05 - val_mae: 0.0029
Epoch 44/50
157/157 [==============================] - 19s 124ms/step - loss: 2.0640e-05 - mae: 0.0033 - val_loss: 1.5712e-05 - val_mae: 0.0031
Epoch 45/50
157/157 [==============================] - 17s 105ms/step - loss: 2.4550e-05 - mae: 0.0035 - val_loss: 1.6947e-05 - val_mae: 0.0033
Epoch 46/50
157/157 [==============================] - 16s 104ms/step - loss: 2.0856e-05 - mae: 0.0033 - val_loss: 1.6156e-05 - val_mae: 0.0032
Epoch 47/50
157/157 [==============================] - 18s 113ms/step - loss: 1.9573e-05 - mae: 0.0032 - val_loss: 1.8016e-05 - val_mae: 0.0034
Epoch 48/50
157/157 [==============================] - 18s 117ms/step - loss: 2.0591e-05 - mae: 0.0033 - val_loss: 1.3119e-05 - val_mae: 0.0028
Epoch 49/50
157/157 [==============================] - 19s 123ms/step - loss: 2.0236e-05 - mae: 0.0032 - val_loss: 1.5123e-05 - val_mae: 0.0030
Epoch 50/50
157/157 [==============================] - 17s 106ms/step - loss: 1.9429e-05 - mae: 0.0032 - val_loss: 1.6442e-05 - val_mae: 0.0032
63/63 [==============================] - 3s 17ms/step

In [17]:


def prepare_data(filename):
    data = filename
    X = data.drop(columns=['A_M1_B1_W1_Z_L', 'A_M1_B1_BC_Z_L', 'A_M1_B1_W1_Z_R', 'A_M1_B1_BC_Z_R', 'A_M1_B1_W2_Z_R', 'A__B1_W1_Z_A_axle_L', 'A__B1_W1_Z_A_axle_R', 'A__B1_W2_Z_A_axle_R', 'V_M1_B1_W1_L', 'V_M1_B1_W1_R', 'QL_M1_B1_W1', 'QR_M1_B1_W1'])
    y = data[["YL_M1_B1_W2", "YR_M1_B1_W2"]]

    # 데이터 스케일링
    scaler_X = StandardScaler()
    X = scaler_X.fit_transform(X)

    # scaler_y = StandardScaler()  # y 데이터에 대한 새로운 스케일러
    # y = scaler_y.fit_transform(y)  # 2차원 배열로 변환

    return X, y

def reshape_data(X, y, N_TIMESTEPS):
    X_list, y_list = [], []
    X_padded = np.vstack([np.zeros((N_TIMESTEPS, X.shape[1])), X])

    for i in range(len(X_padded) - N_TIMESTEPS):
        X_list.append(X_padded[i:i+N_TIMESTEPS])
        y_list.append(y.iloc[i])

    return np.array(X_list), np.array(y_list)


data_s_X, data_s_y = prepare_data(c70_train)   #####################################################

N_TIMESTEPS = 10
N_FEATURES = 26

X_s, y_s = reshape_data(data_s_X, data_s_y, N_TIMESTEPS)

# 트레이닝/테스트 데이터 나누기
X_train_s = X_s[:10001]
y_train_s = y_s[:10001]
X_test_s = X_s[10001:]
y_test_s = y_s[10001:]


# Early stopping
es = EarlyStopping(monitor='val_loss', mode='min', verbose=1, patience=20)

from tensorflow.keras.layers import RepeatVector, TimeDistributed

# DeepAR 스타일의 모델 구축
inputs = tf.keras.Input(shape=(N_TIMESTEPS, N_FEATURES))

# LSTM을 통한 인코딩
x = LSTM(64, return_sequences=True)(inputs)
x = LSTM(128, return_sequences=False)(x)
x = Dropout(0.5)(x)

# 미래 타임스텝에 대한 예측을 위한 RepeatVector
x = RepeatVector(N_TIMESTEPS)(x)

# LSTM을 통한 디코딩
x = LSTM(128, return_sequences=True)(x)
x = LSTM(64, return_sequences=True)(x)
x = Dropout(0.5)(x)

# 각 타임스텝에 대한 출력 값 생성
x = TimeDistributed(Dense(2))(x)

model_deepar = Model(inputs=inputs, outputs=x[:, -1, :])  # 마지막 타임스텝의 출력만 사용

model_deepar.compile(optimizer=tf.keras.optimizers.Adam(learning_rate=0.001), loss='mse', metrics=['mae'])

model_deepar.fit(X_train_s, y_train_s, epochs=50, batch_size=64, validation_data=(X_test_s, y_test_s), callbacks=[es])


# 예측
predictions_s2 = model_deepar.predict(X_test_s)

Epoch 1/50
157/157 [==============================] - 27s 112ms/step - loss: 0.0012 - mae: 0.0241 - val_loss: 6.0138e-04 - val_mae: 0.0194
Epoch 2/50
157/157 [==============================] - 18s 117ms/step - loss: 2.9527e-04 - mae: 0.0130 - val_loss: 4.1632e-04 - val_mae: 0.0161
Epoch 3/50
157/157 [==============================] - 23s 145ms/step - loss: 2.1666e-04 - mae: 0.0110 - val_loss: 2.6189e-04 - val_mae: 0.0128
Epoch 4/50
157/157 [==============================] - 17s 106ms/step - loss: 1.8115e-04 - mae: 0.0099 - val_loss: 2.2980e-04 - val_mae: 0.0119
Epoch 5/50
157/157 [==============================] - 16s 104ms/step - loss: 1.5776e-04 - mae: 0.0092 - val_loss: 1.9451e-04 - val_mae: 0.0108
Epoch 6/50
157/157 [==============================] - 19s 119ms/step - loss: 1.4703e-04 - mae: 0.0088 - val_loss: 1.4757e-04 - val_mae: 0.0094
Epoch 7/50
157/157 [==============================] - 17s 106ms/step - loss: 1.2763e-04 - mae: 0.0083 - val_loss: 1.2826e-04 - val_mae: 0.0088
Epoch 8/50
157/157 [==============================] - 17s 106ms/step - loss: 1.2164e-04 - mae: 0.0081 - val_loss: 1.4765e-04 - val_mae: 0.0096
Epoch 9/50
157/157 [==============================] - 26s 165ms/step - loss: 1.1596e-04 - mae: 0.0079 - val_loss: 1.0873e-04 - val_mae: 0.0082
Epoch 10/50
157/157 [==============================] - 17s 106ms/step - loss: 1.1190e-04 - mae: 0.0077 - val_loss: 1.1087e-04 - val_mae: 0.0085
Epoch 11/50
157/157 [==============================] - 17s 106ms/step - loss: 1.0352e-04 - mae: 0.0074 - val_loss: 8.7520e-05 - val_mae: 0.0073
Epoch 12/50
157/157 [==============================] - 16s 104ms/step - loss: 1.0000e-04 - mae: 0.0073 - val_loss: 8.6453e-05 - val_mae: 0.0074
Epoch 13/50
157/157 [==============================] - 21s 133ms/step - loss: 9.6135e-05 - mae: 0.0071 - val_loss: 9.1952e-05 - val_mae: 0.0074
Epoch 14/50
157/157 [==============================] - 16s 102ms/step - loss: 9.2340e-05 - mae: 0.0069 - val_loss: 8.0073e-05 - val_mae: 0.0070
Epoch 15/50
157/157 [==============================] - 17s 106ms/step - loss: 8.6169e-05 - mae: 0.0067 - val_loss: 5.7879e-05 - val_mae: 0.0059
Epoch 16/50
157/157 [==============================] - 17s 110ms/step - loss: 8.3220e-05 - mae: 0.0066 - val_loss: 7.2432e-05 - val_mae: 0.0069
Epoch 17/50
157/157 [==============================] - 19s 120ms/step - loss: 8.3522e-05 - mae: 0.0066 - val_loss: 6.6915e-05 - val_mae: 0.0065
Epoch 18/50
157/157 [==============================] - 17s 107ms/step - loss: 8.2223e-05 - mae: 0.0065 - val_loss: 6.9301e-05 - val_mae: 0.0067
Epoch 19/50
157/157 [==============================] - 17s 107ms/step - loss: 7.6431e-05 - mae: 0.0063 - val_loss: 5.2880e-05 - val_mae: 0.0058
Epoch 20/50
157/157 [==============================] - 17s 106ms/step - loss: 7.3587e-05 - mae: 0.0061 - val_loss: 4.7178e-05 - val_mae: 0.0054
Epoch 21/50
157/157 [==============================] - 24s 151ms/step - loss: 7.5877e-05 - mae: 0.0062 - val_loss: 4.2058e-05 - val_mae: 0.0051
Epoch 22/50
157/157 [==============================] - 17s 111ms/step - loss: 7.2906e-05 - mae: 0.0060 - val_loss: 5.1959e-05 - val_mae: 0.0056
Epoch 23/50
157/157 [==============================] - 17s 108ms/step - loss: 6.7125e-05 - mae: 0.0058 - val_loss: 3.5198e-05 - val_mae: 0.0047
Epoch 24/50
157/157 [==============================] - 18s 118ms/step - loss: 6.8275e-05 - mae: 0.0059 - val_loss: 4.6491e-05 - val_mae: 0.0054
Epoch 25/50
157/157 [==============================] - 16s 102ms/step - loss: 7.1393e-05 - mae: 0.0059 - val_loss: 5.5005e-05 - val_mae: 0.0059
Epoch 26/50
157/157 [==============================] - 17s 107ms/step - loss: 6.6668e-05 - mae: 0.0057 - val_loss: 4.3049e-05 - val_mae: 0.0054
Epoch 27/50
157/157 [==============================] - 18s 117ms/step - loss: 6.6465e-05 - mae: 0.0058 - val_loss: 4.6039e-05 - val_mae: 0.0055
Epoch 28/50
157/157 [==============================] - 21s 136ms/step - loss: 6.4349e-05 - mae: 0.0057 - val_loss: 4.4344e-05 - val_mae: 0.0053
Epoch 29/50
157/157 [==============================] - 18s 117ms/step - loss: 6.4654e-05 - mae: 0.0056 - val_loss: 4.4043e-05 - val_mae: 0.0053
Epoch 30/50
157/157 [==============================] - 17s 106ms/step - loss: 6.0457e-05 - mae: 0.0055 - val_loss: 4.4517e-05 - val_mae: 0.0054
Epoch 31/50
157/157 [==============================] - 19s 121ms/step - loss: 6.0653e-05 - mae: 0.0055 - val_loss: 3.9429e-05 - val_mae: 0.0051
Epoch 32/50
157/157 [==============================] - 16s 105ms/step - loss: 6.4321e-05 - mae: 0.0056 - val_loss: 3.8602e-05 - val_mae: 0.0050
Epoch 33/50
157/157 [==============================] - 17s 107ms/step - loss: 6.3649e-05 - mae: 0.0056 - val_loss: 3.5638e-05 - val_mae: 0.0047
Epoch 34/50
157/157 [==============================] - 20s 129ms/step - loss: 6.0692e-05 - mae: 0.0055 - val_loss: 3.7390e-05 - val_mae: 0.0050
Epoch 35/50
157/157 [==============================] - 16s 103ms/step - loss: 6.0864e-05 - mae: 0.0055 - val_loss: 4.0331e-05 - val_mae: 0.0051
Epoch 36/50
157/157 [==============================] - 19s 121ms/step - loss: 6.1914e-05 - mae: 0.0055 - val_loss: 3.4176e-05 - val_mae: 0.0047
Epoch 37/50
157/157 [==============================] - 17s 107ms/step - loss: 5.9976e-05 - mae: 0.0054 - val_loss: 3.4984e-05 - val_mae: 0.0048
Epoch 38/50
157/157 [==============================] - 19s 118ms/step - loss: 5.9316e-05 - mae: 0.0054 - val_loss: 2.3064e-05 - val_mae: 0.0038
Epoch 39/50
157/157 [==============================] - 18s 115ms/step - loss: 5.7158e-05 - mae: 0.0053 - val_loss: 4.2122e-05 - val_mae: 0.0054
Epoch 40/50
157/157 [==============================] - 21s 131ms/step - loss: 6.1322e-05 - mae: 0.0055 - val_loss: 2.9007e-05 - val_mae: 0.0043
Epoch 41/50
157/157 [==============================] - 17s 108ms/step - loss: 6.2411e-05 - mae: 0.0055 - val_loss: 2.8313e-05 - val_mae: 0.0043
Epoch 42/50
157/157 [==============================] - 16s 105ms/step - loss: 6.0012e-05 - mae: 0.0054 - val_loss: 2.3276e-05 - val_mae: 0.0039
Epoch 43/50
157/157 [==============================] - 19s 121ms/step - loss: 5.5610e-05 - mae: 0.0053 - val_loss: 2.6958e-05 - val_mae: 0.0042
Epoch 44/50
157/157 [==============================] - 18s 117ms/step - loss: 5.7864e-05 - mae: 0.0054 - val_loss: 2.6062e-05 - val_mae: 0.0041
Epoch 45/50
157/157 [==============================] - 17s 107ms/step - loss: 5.7522e-05 - mae: 0.0053 - val_loss: 2.6453e-05 - val_mae: 0.0041
Epoch 46/50
157/157 [==============================] - 24s 153ms/step - loss: 5.7542e-05 - mae: 0.0053 - val_loss: 3.0817e-05 - val_mae: 0.0045
Epoch 47/50
157/157 [==============================] - 17s 106ms/step - loss: 5.8740e-05 - mae: 0.0054 - val_loss: 3.2644e-05 - val_mae: 0.0047
Epoch 48/50
157/157 [==============================] - 17s 106ms/step - loss: 5.7822e-05 - mae: 0.0054 - val_loss: 2.7409e-05 - val_mae: 0.0043
Epoch 49/50
157/157 [==============================] - 17s 108ms/step - loss: 5.8373e-05 - mae: 0.0053 - val_loss: 2.6682e-05 - val_mae: 0.0042
Epoch 50/50
157/157 [==============================] - 20s 129ms/step - loss: 5.6969e-05 - mae: 0.0053 - val_loss: 3.2201e-05 - val_mae: 0.0046
63/63 [==============================] - 3s 18ms/step

In [18]:
predictions_70c = pd.DataFrame(predictions_s, columns=['YL_M1_B1_W1', 'YR_M1_B1_W1'])
predictions_70c2 = pd.DataFrame(predictions_s2, columns=['YL_M1_B1_W2', 'YR_M1_B1_W2'])

In [19]:
def prepare_data(filename):
    data = filename
    X = data.drop(columns=['Curvature', 'Vertical offset', 'Cross level offset', 'A_M1_B1_W1_Z_L', 'A_M1_B1_BC_Z_L', 'A_M1_B1_W2_Z_L', 'A_M1_B1_W1_Z_R', 'A_M1_B1_BC_Z_R', 'A_M1_B1_W2_Z_R', 'A__B1_W2_Y_A_axle_L', 'A__B1_W1_Z_A_axle_R'])
    y = data[["YL_M1_B1_W1", "YR_M1_B1_W1"]]

    # 데이터 스케일링
    scaler_X = StandardScaler()
    X = scaler_X.fit_transform(X)

    # scaler_y = StandardScaler()  # y 데이터에 대한 새로운 스케일러
    # y = scaler_y.fit_transform(y)  # 2차원 배열로 변환

    return X, y

def reshape_data(X, y, N_TIMESTEPS):
    X_list, y_list = [], []
    X_padded = np.vstack([np.zeros((N_TIMESTEPS, X.shape[1])), X])

    for i in range(len(X_padded) - N_TIMESTEPS):
        X_list.append(X_padded[i:i+N_TIMESTEPS])
        y_list.append(y.iloc[i])

    return np.array(X_list), np.array(y_list)


data_s_X, data_s_y = prepare_data(c100_train)   #####################################################

N_TIMESTEPS = 10
N_FEATURES = 27

X_s, y_s = reshape_data(data_s_X, data_s_y, N_TIMESTEPS)

# 트레이닝/테스트 데이터 나누기
X_train_s = X_s[:10001]
y_train_s = y_s[:10001]
X_test_s = X_s[10001:]
y_test_s = y_s[10001:]


# Early stopping
es = EarlyStopping(monitor='val_loss', mode='min', verbose=1, patience=20)

from tensorflow.keras.layers import RepeatVector, TimeDistributed

# DeepAR 스타일의 모델 구축
inputs = tf.keras.Input(shape=(N_TIMESTEPS, N_FEATURES))

# LSTM을 통한 인코딩
x = LSTM(64, return_sequences=True)(inputs)
x = LSTM(128, return_sequences=False)(x)
x = Dropout(0.5)(x)

# 미래 타임스텝에 대한 예측을 위한 RepeatVector
x = RepeatVector(N_TIMESTEPS)(x)

# LSTM을 통한 디코딩
x = LSTM(128, return_sequences=True)(x)
x = LSTM(64, return_sequences=True)(x)
x = Dropout(0.5)(x)

# 각 타임스텝에 대한 출력 값 생성
x = TimeDistributed(Dense(2))(x)

model_deepar = Model(inputs=inputs, outputs=x[:, -1, :])  # 마지막 타임스텝의 출력만 사용

model_deepar.compile(optimizer=tf.keras.optimizers.Adam(learning_rate=0.001), loss='mse', metrics=['mae'])

model_deepar.fit(X_train_s, y_train_s, epochs=50, batch_size=64, validation_data=(X_test_s, y_test_s), callbacks=[es])


# 예측
predictions_s = model_deepar.predict(X_test_s)

Epoch 1/50
157/157 [==============================] - 31s 139ms/step - loss: 8.6100e-04 - mae: 0.0198 - val_loss: 9.2019e-05 - val_mae: 0.0075
Epoch 2/50
157/157 [==============================] - 19s 123ms/step - loss: 1.5906e-04 - mae: 0.0096 - val_loss: 9.8101e-05 - val_mae: 0.0077
Epoch 3/50
157/157 [==============================] - 19s 120ms/step - loss: 1.0941e-04 - mae: 0.0080 - val_loss: 8.4501e-05 - val_mae: 0.0071
Epoch 4/50
157/157 [==============================] - 17s 107ms/step - loss: 8.8467e-05 - mae: 0.0072 - val_loss: 7.3119e-05 - val_mae: 0.0067
Epoch 5/50
157/157 [==============================] - 17s 109ms/step - loss: 7.8344e-05 - mae: 0.0067 - val_loss: 5.2336e-05 - val_mae: 0.0056
Epoch 6/50
157/157 [==============================] - 19s 123ms/step - loss: 6.9789e-05 - mae: 0.0063 - val_loss: 6.8388e-05 - val_mae: 0.0064
Epoch 7/50
157/157 [==============================] - 19s 121ms/step - loss: 6.2550e-05 - mae: 0.0060 - val_loss: 5.4433e-05 - val_mae: 0.0057
Epoch 8/50
157/157 [==============================] - 21s 136ms/step - loss: 5.7649e-05 - mae: 0.0057 - val_loss: 4.7256e-05 - val_mae: 0.0053
Epoch 9/50
157/157 [==============================] - 19s 122ms/step - loss: 5.2457e-05 - mae: 0.0055 - val_loss: 3.6926e-05 - val_mae: 0.0047
Epoch 10/50
157/157 [==============================] - 17s 106ms/step - loss: 4.9529e-05 - mae: 0.0053 - val_loss: 3.3733e-05 - val_mae: 0.0045
Epoch 11/50
157/157 [==============================] - 17s 106ms/step - loss: 4.4766e-05 - mae: 0.0050 - val_loss: 3.9102e-05 - val_mae: 0.0049
Epoch 12/50
157/157 [==============================] - 17s 107ms/step - loss: 4.3171e-05 - mae: 0.0049 - val_loss: 4.1721e-05 - val_mae: 0.0050
Epoch 13/50
157/157 [==============================] - 18s 117ms/step - loss: 4.0773e-05 - mae: 0.0048 - val_loss: 3.2244e-05 - val_mae: 0.0044
Epoch 14/50
157/157 [==============================] - 23s 148ms/step - loss: 3.8581e-05 - mae: 0.0047 - val_loss: 2.9964e-05 - val_mae: 0.0043
Epoch 15/50
157/157 [==============================] - 16s 105ms/step - loss: 3.6512e-05 - mae: 0.0045 - val_loss: 2.9704e-05 - val_mae: 0.0043
Epoch 16/50
157/157 [==============================] - 19s 120ms/step - loss: 3.4930e-05 - mae: 0.0044 - val_loss: 2.5902e-05 - val_mae: 0.0040
Epoch 17/50
157/157 [==============================] - 17s 106ms/step - loss: 3.1546e-05 - mae: 0.0042 - val_loss: 2.7832e-05 - val_mae: 0.0041
Epoch 18/50
157/157 [==============================] - 17s 106ms/step - loss: 3.1515e-05 - mae: 0.0042 - val_loss: 2.4960e-05 - val_mae: 0.0039
Epoch 19/50
157/157 [==============================] - 17s 106ms/step - loss: 2.8310e-05 - mae: 0.0040 - val_loss: 2.3448e-05 - val_mae: 0.0038
Epoch 20/50
157/157 [==============================] - 19s 119ms/step - loss: 2.7725e-05 - mae: 0.0039 - val_loss: 2.6774e-05 - val_mae: 0.0041
Epoch 21/50
157/157 [==============================] - 22s 143ms/step - loss: 2.8573e-05 - mae: 0.0039 - val_loss: 2.5276e-05 - val_mae: 0.0040
Epoch 22/50
157/157 [==============================] - 17s 105ms/step - loss: 2.6345e-05 - mae: 0.0038 - val_loss: 2.7105e-05 - val_mae: 0.0041
Epoch 23/50
157/157 [==============================] - 19s 118ms/step - loss: 2.5688e-05 - mae: 0.0038 - val_loss: 2.1117e-05 - val_mae: 0.0036
Epoch 24/50
157/157 [==============================] - 16s 104ms/step - loss: 2.5983e-05 - mae: 0.0037 - val_loss: 2.4652e-05 - val_mae: 0.0039
Epoch 25/50
157/157 [==============================] - 17s 106ms/step - loss: 2.4720e-05 - mae: 0.0036 - val_loss: 2.5146e-05 - val_mae: 0.0040
Epoch 26/50
157/157 [==============================] - 17s 109ms/step - loss: 2.4034e-05 - mae: 0.0036 - val_loss: 2.2877e-05 - val_mae: 0.0038
Epoch 27/50
157/157 [==============================] - 21s 136ms/step - loss: 2.4227e-05 - mae: 0.0036 - val_loss: 1.8909e-05 - val_mae: 0.0034
Epoch 28/50
157/157 [==============================] - 18s 113ms/step - loss: 2.3437e-05 - mae: 0.0035 - val_loss: 2.1727e-05 - val_mae: 0.0037
Epoch 29/50
157/157 [==============================] - 17s 109ms/step - loss: 2.3335e-05 - mae: 0.0035 - val_loss: 2.1887e-05 - val_mae: 0.0037
Epoch 30/50
157/157 [==============================] - 17s 105ms/step - loss: 2.3701e-05 - mae: 0.0035 - val_loss: 2.1548e-05 - val_mae: 0.0037
Epoch 31/50
157/157 [==============================] - 19s 120ms/step - loss: 2.2550e-05 - mae: 0.0035 - val_loss: 1.7979e-05 - val_mae: 0.0033
Epoch 32/50
157/157 [==============================] - 17s 107ms/step - loss: 2.2285e-05 - mae: 0.0034 - val_loss: 2.0435e-05 - val_mae: 0.0036
Epoch 33/50
157/157 [==============================] - 19s 119ms/step - loss: 2.3509e-05 - mae: 0.0035 - val_loss: 1.5819e-05 - val_mae: 0.0032
Epoch 34/50
157/157 [==============================] - 18s 117ms/step - loss: 2.2217e-05 - mae: 0.0034 - val_loss: 1.6278e-05 - val_mae: 0.0032
Epoch 35/50
157/157 [==============================] - 16s 102ms/step - loss: 2.3466e-05 - mae: 0.0035 - val_loss: 1.4809e-05 - val_mae: 0.0030
Epoch 36/50
157/157 [==============================] - 18s 117ms/step - loss: 2.0554e-05 - mae: 0.0033 - val_loss: 1.3375e-05 - val_mae: 0.0029
Epoch 37/50
157/157 [==============================] - 16s 105ms/step - loss: 2.2305e-05 - mae: 0.0034 - val_loss: 1.8959e-05 - val_mae: 0.0034
Epoch 38/50
157/157 [==============================] - 19s 119ms/step - loss: 2.1344e-05 - mae: 0.0033 - val_loss: 2.0234e-05 - val_mae: 0.0036
Epoch 39/50
157/157 [==============================] - 17s 106ms/step - loss: 2.2200e-05 - mae: 0.0034 - val_loss: 1.5755e-05 - val_mae: 0.0031
Epoch 40/50
157/157 [==============================] - 23s 148ms/step - loss: 2.1416e-05 - mae: 0.0033 - val_loss: 1.5690e-05 - val_mae: 0.0031
Epoch 41/50
157/157 [==============================] - 17s 105ms/step - loss: 2.1410e-05 - mae: 0.0033 - val_loss: 2.5338e-05 - val_mae: 0.0040
Epoch 42/50
157/157 [==============================] - 17s 106ms/step - loss: 2.2527e-05 - mae: 0.0034 - val_loss: 1.5045e-05 - val_mae: 0.0030
Epoch 43/50
157/157 [==============================] - 19s 120ms/step - loss: 2.1170e-05 - mae: 0.0033 - val_loss: 1.4139e-05 - val_mae: 0.0030
Epoch 44/50
157/157 [==============================] - 18s 113ms/step - loss: 2.1676e-05 - mae: 0.0033 - val_loss: 1.4380e-05 - val_mae: 0.0029
Epoch 45/50
157/157 [==============================] - 17s 107ms/step - loss: 1.9874e-05 - mae: 0.0032 - val_loss: 1.7883e-05 - val_mae: 0.0033
Epoch 46/50
157/157 [==============================] - 22s 138ms/step - loss: 2.1066e-05 - mae: 0.0032 - val_loss: 1.5271e-05 - val_mae: 0.0030
Epoch 47/50
157/157 [==============================] - 18s 112ms/step - loss: 1.9705e-05 - mae: 0.0032 - val_loss: 1.4471e-05 - val_mae: 0.0030
Epoch 48/50
157/157 [==============================] - 18s 116ms/step - loss: 2.0748e-05 - mae: 0.0033 - val_loss: 1.6629e-05 - val_mae: 0.0032
Epoch 49/50
157/157 [==============================] - 16s 102ms/step - loss: 1.8902e-05 - mae: 0.0031 - val_loss: 1.6477e-05 - val_mae: 0.0032
Epoch 50/50
157/157 [==============================] - 19s 119ms/step - loss: 1.9078e-05 - mae: 0.0032 - val_loss: 1.7610e-05 - val_mae: 0.0033
63/63 [==============================] - 3s 19ms/step

In [20]:


def prepare_data(filename):
    data = filename
    X = data.drop(columns=['A_M1_B1_W1_Z_L', 'A_M1_B1_BC_Z_L', 'A_M1_B1_W1_Z_R', 'A_M1_B1_BC_Z_R', 'A_M1_B1_W2_Z_R', 'A__B1_W1_Z_A_axle_L', 'A__B1_W1_Z_A_axle_R', 'A__B1_W2_Z_A_axle_R', 'V_M1_B1_W1_L', 'V_M1_B1_W1_R', 'QL_M1_B1_W1', 'QR_M1_B1_W1'])
    y = data[["YL_M1_B1_W2", "YR_M1_B1_W2"]]

    # 데이터 스케일링
    scaler_X = StandardScaler()
    X = scaler_X.fit_transform(X)

    # scaler_y = StandardScaler()  # y 데이터에 대한 새로운 스케일러
    # y = scaler_y.fit_transform(y)  # 2차원 배열로 변환

    return X, y

def reshape_data(X, y, N_TIMESTEPS):
    X_list, y_list = [], []
    X_padded = np.vstack([np.zeros((N_TIMESTEPS, X.shape[1])), X])

    for i in range(len(X_padded) - N_TIMESTEPS):
        X_list.append(X_padded[i:i+N_TIMESTEPS])
        y_list.append(y.iloc[i])

    return np.array(X_list), np.array(y_list)


data_s_X, data_s_y = prepare_data(c100_train)   #####################################################

N_TIMESTEPS = 10
N_FEATURES = 26

X_s, y_s = reshape_data(data_s_X, data_s_y, N_TIMESTEPS)

# 트레이닝/테스트 데이터 나누기
X_train_s = X_s[:10001]
y_train_s = y_s[:10001]
X_test_s = X_s[10001:]
y_test_s = y_s[10001:]


# Early stopping
es = EarlyStopping(monitor='val_loss', mode='min', verbose=1, patience=20)

from tensorflow.keras.layers import RepeatVector, TimeDistributed

# DeepAR 스타일의 모델 구축
inputs = tf.keras.Input(shape=(N_TIMESTEPS, N_FEATURES))

# LSTM을 통한 인코딩
x = LSTM(64, return_sequences=True)(inputs)
x = LSTM(128, return_sequences=False)(x)
x = Dropout(0.5)(x)

# 미래 타임스텝에 대한 예측을 위한 RepeatVector
x = RepeatVector(N_TIMESTEPS)(x)

# LSTM을 통한 디코딩
x = LSTM(128, return_sequences=True)(x)
x = LSTM(64, return_sequences=True)(x)
x = Dropout(0.5)(x)

# 각 타임스텝에 대한 출력 값 생성
x = TimeDistributed(Dense(2))(x)

model_deepar = Model(inputs=inputs, outputs=x[:, -1, :])  # 마지막 타임스텝의 출력만 사용

model_deepar.compile(optimizer=tf.keras.optimizers.Adam(learning_rate=0.001), loss='mse', metrics=['mae'])

model_deepar.fit(X_train_s, y_train_s, epochs=50, batch_size=64, validation_data=(X_test_s, y_test_s), callbacks=[es])


# 예측
predictions_s2 = model_deepar.predict(X_test_s)

Epoch 1/50
157/157 [==============================] - 26s 108ms/step - loss: 0.0011 - mae: 0.0235 - val_loss: 3.7868e-04 - val_mae: 0.0154
Epoch 2/50
157/157 [==============================] - 22s 139ms/step - loss: 2.9717e-04 - mae: 0.0130 - val_loss: 3.2661e-04 - val_mae: 0.0143
Epoch 3/50
157/157 [==============================] - 16s 99ms/step - loss: 2.0910e-04 - mae: 0.0108 - val_loss: 1.7264e-04 - val_mae: 0.0103
Epoch 4/50
157/157 [==============================] - 17s 106ms/step - loss: 1.6458e-04 - mae: 0.0095 - val_loss: 1.9930e-04 - val_mae: 0.0111
Epoch 5/50
157/157 [==============================] - 17s 106ms/step - loss: 1.5300e-04 - mae: 0.0091 - val_loss: 1.6817e-04 - val_mae: 0.0101
Epoch 6/50
157/157 [==============================] - 16s 101ms/step - loss: 1.3830e-04 - mae: 0.0086 - val_loss: 1.1621e-04 - val_mae: 0.0085
Epoch 7/50
157/157 [==============================] - 18s 112ms/step - loss: 1.2700e-04 - mae: 0.0082 - val_loss: 1.1181e-04 - val_mae: 0.0083
Epoch 8/50
157/157 [==============================] - 16s 102ms/step - loss: 1.1721e-04 - mae: 0.0080 - val_loss: 1.1691e-04 - val_mae: 0.0087
Epoch 9/50
157/157 [==============================] - 20s 126ms/step - loss: 1.1022e-04 - mae: 0.0077 - val_loss: 9.7965e-05 - val_mae: 0.0076
Epoch 10/50
157/157 [==============================] - 18s 112ms/step - loss: 1.0478e-04 - mae: 0.0074 - val_loss: 7.6657e-05 - val_mae: 0.0069
Epoch 11/50
157/157 [==============================] - 16s 100ms/step - loss: 9.9225e-05 - mae: 0.0072 - val_loss: 8.7353e-05 - val_mae: 0.0072
Epoch 12/50
157/157 [==============================] - 16s 101ms/step - loss: 1.0129e-04 - mae: 0.0072 - val_loss: 7.7223e-05 - val_mae: 0.0070
Epoch 13/50
157/157 [==============================] - 16s 101ms/step - loss: 9.2011e-05 - mae: 0.0069 - val_loss: 8.3901e-05 - val_mae: 0.0071
Epoch 14/50
157/157 [==============================] - 15s 97ms/step - loss: 8.6131e-05 - mae: 0.0066 - val_loss: 8.3400e-05 - val_mae: 0.0073
Epoch 15/50
157/157 [==============================] - 16s 100ms/step - loss: 8.5861e-05 - mae: 0.0066 - val_loss: 6.4811e-05 - val_mae: 0.0064
Epoch 16/50
157/157 [==============================] - 23s 146ms/step - loss: 8.4242e-05 - mae: 0.0065 - val_loss: 7.9565e-05 - val_mae: 0.0070
Epoch 17/50
157/157 [==============================] - 16s 101ms/step - loss: 7.9016e-05 - mae: 0.0064 - val_loss: 6.6679e-05 - val_mae: 0.0064
Epoch 18/50
157/157 [==============================] - 17s 107ms/step - loss: 7.9482e-05 - mae: 0.0064 - val_loss: 6.1763e-05 - val_mae: 0.0062
Epoch 19/50
157/157 [==============================] - 17s 106ms/step - loss: 7.4355e-05 - mae: 0.0062 - val_loss: 7.8630e-05 - val_mae: 0.0073
Epoch 20/50
157/157 [==============================] - 15s 98ms/step - loss: 7.7007e-05 - mae: 0.0062 - val_loss: 6.1341e-05 - val_mae: 0.0063
Epoch 21/50
157/157 [==============================] - 16s 101ms/step - loss: 7.3551e-05 - mae: 0.0060 - val_loss: 7.3815e-05 - val_mae: 0.0073
Epoch 22/50
157/157 [==============================] - 17s 110ms/step - loss: 6.9389e-05 - mae: 0.0059 - val_loss: 5.4860e-05 - val_mae: 0.0058
Epoch 23/50
157/157 [==============================] - 21s 133ms/step - loss: 6.7526e-05 - mae: 0.0058 - val_loss: 4.9631e-05 - val_mae: 0.0055
Epoch 24/50
157/157 [==============================] - 17s 105ms/step - loss: 6.7632e-05 - mae: 0.0058 - val_loss: 4.4473e-05 - val_mae: 0.0053
Epoch 25/50
157/157 [==============================] - 15s 98ms/step - loss: 6.5965e-05 - mae: 0.0057 - val_loss: 4.5465e-05 - val_mae: 0.0054
Epoch 26/50
157/157 [==============================] - 18s 113ms/step - loss: 6.7819e-05 - mae: 0.0058 - val_loss: 4.8528e-05 - val_mae: 0.0056
Epoch 27/50
157/157 [==============================] - 16s 100ms/step - loss: 6.3096e-05 - mae: 0.0056 - val_loss: 4.4197e-05 - val_mae: 0.0053
Epoch 28/50
157/157 [==============================] - 17s 108ms/step - loss: 6.3961e-05 - mae: 0.0056 - val_loss: 5.1762e-05 - val_mae: 0.0058
Epoch 29/50
157/157 [==============================] - 16s 99ms/step - loss: 6.9818e-05 - mae: 0.0058 - val_loss: 4.0381e-05 - val_mae: 0.0050
Epoch 30/50
157/157 [==============================] - 16s 101ms/step - loss: 6.3335e-05 - mae: 0.0056 - val_loss: 4.6387e-05 - val_mae: 0.0053
Epoch 31/50
157/157 [==============================] - 22s 143ms/step - loss: 6.4277e-05 - mae: 0.0056 - val_loss: 3.9908e-05 - val_mae: 0.0051
Epoch 32/50
157/157 [==============================] - 16s 101ms/step - loss: 6.5303e-05 - mae: 0.0056 - val_loss: 5.1414e-05 - val_mae: 0.0056
Epoch 33/50
157/157 [==============================] - 16s 101ms/step - loss: 6.2355e-05 - mae: 0.0055 - val_loss: 4.0473e-05 - val_mae: 0.0050
Epoch 34/50
157/157 [==============================] - 18s 117ms/step - loss: 6.0357e-05 - mae: 0.0054 - val_loss: 3.9891e-05 - val_mae: 0.0051
Epoch 35/50
157/157 [==============================] - 16s 102ms/step - loss: 6.1332e-05 - mae: 0.0055 - val_loss: 4.1897e-05 - val_mae: 0.0052
Epoch 36/50
157/157 [==============================] - 16s 103ms/step - loss: 5.9928e-05 - mae: 0.0054 - val_loss: 3.0672e-05 - val_mae: 0.0044
Epoch 37/50
157/157 [==============================] - 16s 101ms/step - loss: 6.0633e-05 - mae: 0.0054 - val_loss: 4.1082e-05 - val_mae: 0.0051
Epoch 38/50
157/157 [==============================] - 20s 126ms/step - loss: 6.1326e-05 - mae: 0.0055 - val_loss: 2.3624e-05 - val_mae: 0.0039
Epoch 39/50
157/157 [==============================] - 19s 118ms/step - loss: 5.7928e-05 - mae: 0.0053 - val_loss: 3.5810e-05 - val_mae: 0.0048
Epoch 40/50
157/157 [==============================] - 16s 100ms/step - loss: 6.1016e-05 - mae: 0.0055 - val_loss: 3.0058e-05 - val_mae: 0.0043
Epoch 41/50
157/157 [==============================] - 17s 108ms/step - loss: 5.7169e-05 - mae: 0.0053 - val_loss: 3.2463e-05 - val_mae: 0.0046
Epoch 42/50
157/157 [==============================] - 17s 110ms/step - loss: 5.7857e-05 - mae: 0.0053 - val_loss: 3.0666e-05 - val_mae: 0.0043
Epoch 43/50
157/157 [==============================] - 16s 102ms/step - loss: 5.6505e-05 - mae: 0.0053 - val_loss: 4.0603e-05 - val_mae: 0.0050
Epoch 44/50
157/157 [==============================] - 19s 124ms/step - loss: 5.9842e-05 - mae: 0.0054 - val_loss: 3.0801e-05 - val_mae: 0.0044
Epoch 45/50
157/157 [==============================] - 16s 103ms/step - loss: 5.7359e-05 - mae: 0.0053 - val_loss: 2.9336e-05 - val_mae: 0.0043
Epoch 46/50
157/157 [==============================] - 15s 97ms/step - loss: 5.5170e-05 - mae: 0.0052 - val_loss: 3.4836e-05 - val_mae: 0.0048
Epoch 47/50
157/157 [==============================] - 18s 117ms/step - loss: 5.4848e-05 - mae: 0.0052 - val_loss: 2.1655e-05 - val_mae: 0.0037
Epoch 48/50
157/157 [==============================] - 16s 101ms/step - loss: 5.5932e-05 - mae: 0.0052 - val_loss: 2.7576e-05 - val_mae: 0.0042
Epoch 49/50
157/157 [==============================] - 19s 119ms/step - loss: 5.5894e-05 - mae: 0.0053 - val_loss: 3.7370e-05 - val_mae: 0.0050
Epoch 50/50
157/157 [==============================] - 15s 98ms/step - loss: 5.6287e-05 - mae: 0.0053 - val_loss: 2.7914e-05 - val_mae: 0.0042
63/63 [==============================] - 3s 17ms/step

In [21]:
predictions_100c = pd.DataFrame(predictions_s, columns=['YL_M1_B1_W1', 'YR_M1_B1_W1'])
predictions_100c2 = pd.DataFrame(predictions_s2, columns=['YL_M1_B1_W2', 'YR_M1_B1_W2'])

In [22]:
answer_sample = pd.read_csv('/content/drive/My Drive/철도/answer_sample.csv')
c30 = pd.concat([predictions_30c,predictions_30c2],axis=1)
c40 = pd.concat([predictions_40c,predictions_40c2],axis=1)
c50 = pd.concat([predictions_50c,predictions_50c2],axis=1)
c70 = pd.concat([predictions_70c,predictions_70c2],axis=1)
c100 = pd.concat([predictions_100c,predictions_100c2],axis=1)

In [23]:
c30  = pd.DataFrame(c30, columns=["YL_M1_B1_W1", "YR_M1_B1_W1", "YL_M1_B1_W2", "YR_M1_B1_W2"])
c40  = pd.DataFrame(c40, columns=["YL_M1_B1_W1", "YR_M1_B1_W1", "YL_M1_B1_W2", "YR_M1_B1_W2"])
c50  = pd.DataFrame(c50, columns=["YL_M1_B1_W1", "YR_M1_B1_W1", "YL_M1_B1_W2", "YR_M1_B1_W2"])
c70  = pd.DataFrame(c70, columns=["YL_M1_B1_W1", "YR_M1_B1_W1", "YL_M1_B1_W2", "YR_M1_B1_W2"])
c100  = pd.DataFrame(c100, columns=["YL_M1_B1_W1", "YR_M1_B1_W1", "YL_M1_B1_W2", "YR_M1_B1_W2"])

In [24]:
c30.columns = ['YL_M1_B1_W1_c30', 'YR_M1_B1_W1_c30', 'YL_M1_B1_W2_c30', 'YR_M1_B1_W2_c30']
c40.columns = ['YL_M1_B1_W1_c40', 'YR_M1_B1_W1_c40', 'YL_M1_B1_W2_c40', 'YR_M1_B1_W2_c40']
c50.columns = ['YL_M1_B1_W1_c50', 'YR_M1_B1_W1_c50', 'YL_M1_B1_W2_c50', 'YR_M1_B1_W2_c50']
c70.columns = ['YL_M1_B1_W1_c70', 'YR_M1_B1_W1_c70', 'YL_M1_B1_W2_c70', 'YR_M1_B1_W2_c70']
c100.columns = ['YL_M1_B1_W1_c100', 'YR_M1_B1_W1_c100', 'YL_M1_B1_W2_c100', 'YR_M1_B1_W2_c100']

In [25]:
answer2 = pd.concat([answer_sample.Distance,c30,c40,c50,c70,c100], axis=1)

In [26]:
answer2

,Distance,YL_M1_B1_W1_c30,YR_M1_B1_W1_c30,YL_M1_B1_W2_c30,YR_M1_B1_W2_c30,YL_M1_B1_W1_c40,YR_M1_B1_W1_c40,YL_M1_B1_W2_c40,YR_M1_B1_W2_c40,YL_M1_B1_W1_c50,...,YL_M1_B1_W2_c50,YR_M1_B1_W2_c50,YL_M1_B1_W1_c70,YR_M1_B1_W1_c70,YL_M1_B1_W2_c70,YR_M1_B1_W2_c70,YL_M1_B1_W1_c100,YR_M1_B1_W1_c100,YL_M1_B1_W2_c100,YR_M1_B1_W2_c100
0,2500.25,0.021011,0.000561,0.044664,-0.030090,0.002714,0.007235,-0.004830,0.008967,0.009605,...,-0.002854,0.007505,0.010698,0.005484,-0.004044,0.008491,0.009935,0.006552,-0.003808,0.008449
1,2500.50,-0.003516,0.011637,-0.006212,0.010346,-0.002044,0.008441,0.011871,-0.007901,-0.001520,...,0.009938,-0.005174,-0.006434,0.009810,0.010753,-0.005876,-0.004632,0.008645,0.008023,-0.002847
2,2500.75,-0.006366,0.011134,0.003692,0.001595,-0.007339,0.011898,0.006406,-0.003792,-0.007177,...,0.006340,-0.002528,-0.010609,0.010505,0.006946,-0.004182,-0.010056,0.010169,0.006999,-0.002435
3,2501.00,-0.004510,0.007682,0.001047,0.003195,-0.004953,0.008980,0.003915,-0.001714,-0.005643,...,0.005526,-0.002172,-0.007203,0.006657,0.005290,-0.003604,-0.004978,0.004826,0.004712,-0.000885
4,2501.25,-0.003268,0.005388,0.002483,0.001886,-0.001834,0.006029,0.003046,-0.000882,-0.002580,...,0.004098,-0.001065,-0.002693,0.002363,0.003390,-0.002213,-0.000915,0.001582,0.003538,-0.000345
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1994,2998.75,-0.003297,0.004280,0.005259,0.002574,-0.000131,0.004680,0.005309,-0.001902,0.003098,...,0.002951,-0.000357,0.001687,0.000543,0.002951,-0.000226,0.002559,-0.000638,0.006624,-0.002223
1995,2999.00,-0.007496,0.008841,-0.005708,0.012000,-0.005177,0.009387,-0.006992,0.009208,-0.003321,...,-0.006655,0.008747,-0.004910,0.006195,-0.008808,0.008892,-0.004979,0.006996,-0.003265,0.005413
1996,2999.25,-0.004842,0.006815,-0.011927,0.016316,-0.002276,0.006583,-0.011904,0.014013,-0.003000,...,-0.011962,0.014394,-0.004136,0.005316,-0.017188,0.015877,-0.002835,0.005830,-0.011272,0.011886
1997,2999.50,0.005060,-0.003822,-0.011849,0.014841,0.007708,-0.002991,-0.011110,0.014029,0.005001,...,-0.012392,0.015877,0.006574,-0.003925,-0.017856,0.017425,0.007721,-0.004032,-0.013584,0.014017
1998,2999.75,0.002249,-0.003237,-0.001836,0.005579,0.005405,-0.000726,-0.001162,0.005413,0.006660,...,-0.005220,0.010177,0.007979,-0.003866,-0.006255,0.008998,0.007328,-0.002913,-0.006131,0.008097

In [28]:
answer2.to_csv('/content/drive/My Drive/철도/answer20230826_ar_c.csv', index=False)

In [31]:
answer1 = pd.read_csv('/content/drive/My Drive/철도/answer20230826_ar_s.csv')
answer = pd.concat([answer1,answer2], axis=1)

In [32]:
answer

,Distance,YL_M1_B1_W1_s30,YR_M1_B1_W1_s30,YL_M1_B1_W2_s30,YR_M1_B1_W2_s30,YL_M1_B1_W1_s40,YR_M1_B1_W1_s40,YL_M1_B1_W2_s40,YR_M1_B1_W2_s40,YL_M1_B1_W1_s50,...,YL_M1_B1_W2_c50,YR_M1_B1_W2_c50,YL_M1_B1_W1_c70,YR_M1_B1_W1_c70,YL_M1_B1_W2_c70,YR_M1_B1_W2_c70,YL_M1_B1_W1_c100,YR_M1_B1_W1_c100,YL_M1_B1_W2_c100,YR_M1_B1_W2_c100
0,2500.25,0.028696,-0.004394,0.062964,-0.047209,0.005088,0.004656,0.000913,0.003848,0.011418,...,-0.002854,0.007505,0.010698,0.005484,-0.004044,0.008491,0.009935,0.006552,-0.003808,0.008449
1,2500.50,-0.009338,0.018618,-0.011982,0.023495,-0.001020,0.007181,0.010019,-0.005364,-0.004725,...,0.009938,-0.005174,-0.006434,0.009810,0.010753,-0.005876,-0.004632,0.008645,0.008023,-0.002847
2,2500.75,-0.004410,0.011144,0.010570,-0.000342,-0.005577,0.009786,0.003779,-0.000228,-0.007534,...,0.006340,-0.002528,-0.010609,0.010505,0.006946,-0.004182,-0.010056,0.010169,0.006999,-0.002435
3,2501.00,-0.001958,0.006689,0.004273,0.005091,-0.004674,0.008318,0.004108,-0.001283,-0.007510,...,0.005526,-0.002172,-0.007203,0.006657,0.005290,-0.003604,-0.004978,0.004826,0.004712,-0.000885
4,2501.25,0.001669,0.002719,0.005722,0.003122,-0.001619,0.004846,0.003738,-0.001576,-0.003910,...,0.004098,-0.001065,-0.002693,0.002363,0.003390,-0.002213,-0.000915,0.001582,0.003538,-0.000345
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1994,2998.75,0.002040,0.001348,0.002698,0.005167,0.002212,0.000867,0.002002,0.000246,0.001704,...,0.002951,-0.000357,0.001687,0.000543,0.002951,-0.000226,0.002559,-0.000638,0.006624,-0.002223
1995,2999.00,-0.002053,0.005068,-0.008352,0.014076,-0.002647,0.005451,-0.006235,0.007199,-0.004177,...,-0.006655,0.008747,-0.004910,0.006195,-0.008808,0.008892,-0.004979,0.006996,-0.003265,0.005413
1996,2999.25,-0.000109,0.003812,-0.010085,0.014700,-0.000649,0.003680,-0.009022,0.009268,-0.002894,...,-0.011962,0.014394,-0.004136,0.005316,-0.017188,0.015877,-0.002835,0.005830,-0.011272,0.011886
1997,2999.50,0.007347,-0.002344,-0.009122,0.013326,0.007603,-0.004494,-0.008075,0.008452,0.004040,...,-0.012392,0.015877,0.006574,-0.003925,-0.017856,0.017425,0.007721,-0.004032,-0.013584,0.014017
1998,2999.75,0.005471,0.000045,-0.002789,0.006975,0.006934,-0.003644,-0.001577,0.003391,0.003192,...,-0.005220,0.010177,0.007979,-0.003866,-0.006255,0.008998,0.007328,-0.002913,-0.006131,0.008097

In [33]:
answer.to_csv('/content/drive/My Drive/철도/answer20230826_ar.csv', index=False)